'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const {run}=require('./0087_funded_completion_harness.cjs'),{support}=require('./0087_funded_completion_test_support.cjs');
async function main(){let historical;await run(async c=>{
 const h=support(c);let checks=0;const check=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;};
 check(c.target("SELECT jsonb_agg(to_jsonb(x) ORDER BY alignment_id) FROM private.funded_movement_completion_requests x;"),historical.requests,'upgrade preserves original request rows');
 check(c.target("SELECT jsonb_agg(to_jsonb(x)-'completion_method' ORDER BY alignment_id) FROM private.funded_movement_completions x;"),historical.completions,'upgrade preserves original completion fields');
 check(c.target("SELECT bool_and(completion_method='requester_confirmed') FROM private.funded_movement_completions;"),'t','old completions truthfully requester-confirmed');
 check(c.target("SELECT count(*)=2 AND bool_and(response_deadline_at=requested_at+interval '12 hours') FROM private.funded_completion_response_windows;"),'t','old pending and settled requests bind deterministic windows');
 const denied=(f,key,actor,reason)=>{const before=h.state(),r=c.result(f,key,actor,reason);check(r.ok,false,key+' denied');check(h.state(),before,'denial atomic');};
 for(const zero of [false,true]){
  const f=c.fresh({started:true,zero});const before=h.money();
  const unrequested=c.result(f,h.read,f.requester).rows[0];check(unrequested.can_dispute_completion,false,'no request no dispute');check(unrequested.response_deadline_at,null,'no request no deadline');
  denied(f,h.dispute,f.requester,'completion_concern');
  const noRequest=h.state();assert.throws(()=>c.target(`BEGIN; SELECT set_config('request.jwt.claim.sub','${f.offerer}',true); SELECT private.finalize_funded_completion('${f.need}','response_timeout'); COMMIT;`),/23514: Exact offerer completion request required/);checks++;check(h.state(),noRequest,'no request cannot timeout or move money');
  h.requested(f);check(h.money(),before,'request/deadline no money');
  check(c.target(`SELECT w.response_deadline_at=w.requested_at+interval '12 hours' AND w.requested_at=q.requested_at AND q.requested_at=j.completion_requested_at FROM private.funded_completion_response_windows w JOIN private.funded_movement_completion_requests q USING(alignment_id) JOIN public.journeys j ON j.id=w.journey_id WHERE w.alignment_id='${f.alignment}';`),'t','one event exact twelve hours');
  const requester=c.result(f,h.read,f.requester).rows[0],offerer=c.result(f,h.read,f.offerer).rows[0];
  check(requester.can_confirm_completion,true,'requester confirm');check(requester.can_dispute_completion,true,'requester dispute');check(offerer.can_confirm_completion,false,'offerer not confirmer');check(offerer.can_dispute_completion,false,'offerer not reviewer');
  for(const actor of [f.offerer,f.traveller,'00000000-0000-4000-8000-000000000087'])denied(f,h.dispute,actor,'completion_concern');
  for(const category of ['',null,'bad',' completion_concern '])denied(f,h.dispute,f.requester,category===null?'NULL':category);
  const beforeReview=h.money();check(c.result(f,h.dispute,f.requester,'completion_concern').ok,true,'explicit requester review');
  check(h.money(),beforeReview,'review changes no money/completion credit/rating');
  const review=c.result(f,h.read,f.offerer).rows[0];check(review.dispute_active,true,'review visible');check(review.settlement_state,'under_review','under review state');check(review.completion_method,null,'no completion fabricated');check(review.can_confirm_completion,false,'no confirm capability');check(review.can_dispute_completion,false,'no duplicate capability');
  const replay=h.state();check(c.result(f,h.dispute,f.requester,'completion_concern').ok,true,'exact review replay');check(h.state(),replay,'replay no writes');denied(f,h.dispute,f.requester,'movement_concern');denied(f,h.confirm,f.requester);
  const frozen=h.state();assert.throws(()=>c.target(`BEGIN; SELECT set_config('request.jwt.claim.sub','${f.requester}',true); INSERT INTO private.funded_movement_completions VALUES('${f.alignment}','${f.agreement}','${f.journey}',clock_timestamp(),'requester_confirmed'); COMMIT;`),/23514: Completion is under review/);checks++;check(h.state(),frozen,'trusted completion cannot coexist with review');
  // Expiry does not invalidate an already admitted review or allow timeout.
  const restore=h.instrument('public.'+h.read+'(uuid)',"clock_timestamp()+interval '2 days'");try{check(c.result(f,h.read,f.offerer).rows[0].dispute_active,true,'review survives deadline');check(h.money(),beforeReview,'expired review retains held funds');}finally{restore();}
  for(const kind of ['movement_hold_release','requester_platform_charge','movement_contribution_settlement','offering_platform_charge']){
   assert.throws(()=>c.target(`BEGIN; SELECT set_config('request.jwt.claim.sub','${f.requester}',true); INSERT INTO private.wallet_transactions(transaction_kind,currency,alignment_id,financial_component_id,idempotency_key) SELECT '${kind}','NGN','${f.alignment}',id,'${kind}:'||id FROM private.financial_components WHERE agreement_id='${f.agreement}' AND amount_minor>0 LIMIT 1; COMMIT;`),/Completion is under review/);checks++;
  }
  const done=c.fresh({started:true,zero});h.requested(done);check(c.result(done,h.confirm,done.requester).rows[0].completion_method,'requester_confirmed','truthful explicit confirmation');
  const expired=c.fresh({started:true,zero});h.requested(expired,{expired:true});const beforeTimeout=h.state();
  const balances=()=>c.target(`SELECT jsonb_build_object('held',(SELECT coalesce(sum(CASE WHEN p.direction='credit' THEN p.amount_minor::numeric ELSE -p.amount_minor::numeric END),0) FROM private.wallet_postings p JOIN private.wallet_accounts a ON a.id=p.account_id WHERE a.member_id='${expired.requester}' AND a.account_kind='member_held'),'withdrawable',(SELECT coalesce(sum(CASE WHEN p.direction='credit' THEN p.amount_minor::numeric ELSE -p.amount_minor::numeric END),0) FROM private.wallet_postings p JOIN private.wallet_accounts a ON a.id=p.account_id WHERE a.member_id='${expired.offerer}' AND a.account_kind='member_withdrawable'),'revenue',(SELECT coalesce(sum(CASE WHEN p.direction='credit' THEN p.amount_minor::numeric ELSE -p.amount_minor::numeric END),0) FROM private.wallet_postings p JOIN private.wallet_accounts a ON a.id=p.account_id WHERE a.account_kind='platform_revenue'));`);
  const oldBalances=JSON.parse(balances()),amounts=JSON.parse(c.target(`SELECT jsonb_object_agg(component_key,amount_minor) FROM private.financial_components WHERE agreement_id='${expired.agreement}';`));
  check(c.target(`SELECT NOT EXISTS(SELECT 1 FROM private.funded_movement_completions WHERE alignment_id='${expired.alignment}') AND response_deadline_at<clock_timestamp() FROM private.funded_completion_response_windows WHERE alignment_id='${expired.alignment}';`),'t','expired but lazy completion not yet materialized');
  denied(expired,h.dispute,expired.requester,'completion_concern');check(h.state(),beforeTimeout,'late dispute cannot exploit lazy execution');
  const timed=c.result(expired,h.read,expired.offerer);check(timed.ok,true,'offerer refresh materializes timeout');check(timed.rows[0].completion_method,'response_timeout','silence never confirmation');check(timed.rows[0].settlement_state,'settled','timeout settled');check(timed.rows[0].dispute_active,false,'timeout no admin review');
  const finalBalances=JSON.parse(balances());check(finalBalances.held,oldBalances.held-amounts.requester_platform_share-amounts.movement_contribution,'held debit exact R+C');check(finalBalances.withdrawable,oldBalances.withdrawable+amounts.movement_contribution-amounts.offering_platform_share,'offerer net exact C-O');check(finalBalances.revenue,oldBalances.revenue+amounts.requester_platform_share+amounts.offering_platform_share,'platform exact R+O');
  check(c.target(`SELECT a.status='completed' AND j.status='completed' AND (SELECT count(*) FROM private.completed_movement_principals WHERE alignment_id=a.id)=2 AND NOT EXISTS(SELECT 1 FROM private.completed_movement_ratings WHERE alignment_id=a.id) FROM public.alignments a JOIN public.journeys j ON j.alignment_id=a.id WHERE a.id='${expired.alignment}';`),'t','timeout credit both principals without rating');
  check(c.target(`SELECT bool_and((fc.amount_minor=0 AND NOT EXISTS(SELECT 1 FROM private.wallet_transactions t WHERE t.financial_component_id=fc.id AND t.transaction_kind<>'movement_hold')) OR (fc.amount_minor>0 AND (SELECT count(*) FROM private.wallet_transactions t WHERE t.financial_component_id=fc.id AND t.transaction_kind IN('requester_platform_charge','movement_contribution_settlement','offering_platform_charge'))=1)) FROM private.financial_components fc WHERE fc.agreement_id='${expired.agreement}';`),'t','one exact settlement per positive stored component');
  c.target(`SELECT private.assert_funded_coordination_entry('${expired.alignment}');`);checks++;
  const replayTimeout=h.state();check(c.result(expired,h.read,expired.requester).ok,true,'timeout read replay');check(c.result(expired,h.confirm,expired.requester).ok,true,'requester confirm after timeout idempotent');check(h.state(),replayTimeout,'no duplicate ledger/completion/reputation');denied(expired,h.dispute,expired.requester,'completion_concern');
 }
 for(const zero of [false,true]){
  const f=c.fresh({started:true,zero});h.requested(f,{expired:true});
  check(c.target(`SELECT count(*) FROM private.funded_movement_completions WHERE alignment_id='${f.alignment}';`),'0','stale confirm has no lazy terminal receipt');
  const before=h.economics(f),result=c.result(f,h.confirm,f.requester);
  check(result.ok,true,'direct stale authenticated confirm succeeds');check(result.rows[0].completion_method,'response_timeout','late direct confirm never requester-confirmed');
  h.assertSettlement(f,before);checks++;const replay=h.state();check(c.result(f,h.confirm,f.requester).rows[0].completion_method,'response_timeout','late confirm replay retains timeout truth');check(h.state(),replay,'late confirm replay creates zero duplicates');
 }
 const pre=c.fresh();denied(pre,h.request,pre.offerer);denied(pre,h.dispute,pre.requester,'completion_concern');
 const noStart=h.state();assert.throws(()=>c.target(`BEGIN; SELECT set_config('request.jwt.claim.sub','${pre.offerer}',true); SELECT private.finalize_funded_completion('${pre.need}','response_timeout'); COMMIT;`),/23514: Exact offerer completion request required/);checks++;check(h.state(),noStart,'no authoritative start cannot timeout or move money');
 check(c.result(pre,'open_my_funded_movement_dispute',pre.offerer,'movement_concern').ok,true,'0086 pre-start intake unchanged');denied(pre,h.request,pre.offerer);
 for(const table of ['funded_completion_response_windows','funded_completion_disputes']){
  check(c.target(`SELECT relrowsecurity FROM pg_class WHERE oid='private.${table}'::regclass;`),'t','RLS '+table);
  for(const role of ['anon','authenticated','service_role'])for(const privilege of ['SELECT','INSERT','UPDATE','DELETE','TRUNCATE'])check(c.target(`SELECT has_table_privilege('${role}','private.${table}','${privilege}');`),'f',role+' '+privilege);
  for(const command of [`UPDATE private.${table} SET alignment_id=alignment_id WHERE false`,`DELETE FROM private.${table} WHERE false`,`TRUNCATE private.${table} CASCADE`]){assert.throws(()=>c.target('BEGIN; '+command+'; ROLLBACK;'),/23514: Wallet ledger history is append-only/);checks++;}
 }
 for(const name of [h.read,h.request,h.confirm])check(c.target(`SELECT pronargs=1 AND proargnames[1]='p_movement_need_id' FROM pg_proc WHERE oid='public.${name}(uuid)'::regprocedure;`),'t','need only '+name);
 for(const signature of ['private.require_journey_completion_metadata()','private.bind_completion_response_window()','private.require_completion_dispute_actor()','private.reject_completion_review_progress()','private.finalize_funded_completion(uuid,text)'])for(const role of ['anon','authenticated','service_role'])check(c.target(`SELECT has_function_privilege('${role}','${signature}','EXECUTE');`),'f','private no app execute');
 for(const signature of ['public.'+h.read+'(uuid)','public.'+h.request+'(uuid)','public.'+h.confirm+'(uuid)','public.'+h.dispute+'(uuid,text)'])for(const role of ['anon','authenticated','service_role'])check(c.target(`SELECT has_function_privilege('${role}','${signature}','EXECUTE');`),role==='authenticated'?'t':'f','auth-only RPC');
 const forged=c.fresh({started:true}),other=c.fresh({started:true});h.requested(forged);h.requested(other);
 for(const [agreement,journey,actor] of [[other.agreement,forged.journey,forged.requester],[forged.agreement,other.journey,forged.requester],[forged.agreement,forged.journey,forged.offerer]]){
  const before=h.state();assert.throws(()=>c.target(`BEGIN; SELECT set_config('request.jwt.claim.sub','${forged.requester}',true); INSERT INTO private.funded_completion_disputes VALUES('${forged.alignment}','${agreement}','${journey}','${actor}',clock_timestamp(),'completion_concern'); COMMIT;`),/23514|42501/);checks++;check(h.state(),before,'forged graph/actor atomic');
 }
 for(const mode of ['IMMEDIATE','DEFERRED']){const f=c.fresh({started:true});h.requested(f);c.target('BEGIN; SET CONSTRAINTS ALL '+mode+'; '+c.action(f,h.confirm,f.requester)+' COMMIT;');check(c.result(f,h.read,f.offerer).rows[0].completion_method,'requester_confirmed','caller constraint mode '+mode);}
 const output={passed:checks,failed:0};fs.writeFileSync('docs/0087-behavior-results.json',JSON.stringify(output,null,2)+'\n');console.log('PASS '+checks+' PostgreSQL 0087 behavior assertions');
 },{beforeInstall(c){const pending=c.fresh({started:true}),completed=c.fresh({started:true});for(const f of [pending,completed])assert.equal(c.result(f,'request_my_funded_movement_completion',f.offerer).ok,true);assert.equal(c.result(completed,'confirm_my_funded_movement_completion',completed.requester).ok,true);historical={requests:c.target("SELECT jsonb_agg(to_jsonb(x) ORDER BY alignment_id) FROM private.funded_movement_completion_requests x;"),completions:c.target("SELECT jsonb_agg(to_jsonb(x) ORDER BY alignment_id) FROM private.funded_movement_completions x;")};}});}
if(require.main===module)main().catch(e=>{console.error(e.stack);process.exitCode=1;});module.exports={main};
