'use strict';
const assert=require('node:assert/strict');
const {run}=require('./0090_trusted_requester_priority_harness.cjs'),{support}=require('./0090_trusted_requester_priority_test_support.cjs');
async function main(){await run(async c=>{const h=support(c);let checks=0;const check=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;};
 const n=h.requester(),other=h.requester(),old=h.offering(1),veteran=h.offering(1),waiter=h.offering(4),fresh=h.offering(1);
 check(h.list(n).rows,[],'empty owned pool');const stale=h.offer(n,old,{wait:120});c.target(`UPDATE private.offering_movement_availability SET status='withdrawn' WHERE id='${old.availability_id}';`);
 for(const role of ['offering_member','primary_requester']){const f=h.completed(veteran.member_id,role);check(h.rate(f,role==='offering_member'?f.requester:f.offerer,5).ok,true,'authoritative rating');}
 check(h.history(fresh.member_id),20,'no rating neutral requester reputation');check(h.history(veteran.member_id)>20,true,'history confidence beats neutral');
 const vo=h.offer(n,veteran),wo=h.offer(n,waiter,{wait:60}),fo=h.offer(n,fresh);
 check(h.list(n).rows.map(x=>x.movement_offer_id),[vo,wo,fo],'trusted history/reputation/wait tradeoff');check(h.list(n,1).rows.map(x=>x.movement_offer_id),[vo],'invalid old candidate cannot consume limit');check(h.list(n,2).rows.map(x=>x.movement_offer_id),[vo,wo],'highest ranked valid candidates');
 const keys=h.fields.slice().sort();for(const row of h.list(n).rows){check(Object.keys(row).sort(),keys,'exact sixteen safe fields');check(row.offer_status,'pending','only pending');}
 const beforeMoney=h.money(),beforeOps=h.operations();for(let i=0;i<3;i++)check(h.list(n).rows.map(x=>x.movement_offer_id),[vo,wo,fo],'deterministic repeated order');check(h.money(),beforeMoney,'no money/member/history writes');check(h.operations(),beforeOps,'no offers/interests/capacity/alignments/journeys/timestamp writes');
 const forbidden=h.list(n,20,other.member_id),missing=h.list(n,20,other.member_id,'authenticated','00000000-0000-4000-8000-000000000000');check(forbidden.ok,false,'foreign denied');check(forbidden,missing,'foreign and missing indistinguishable');
 for(const limit of [null,0,51])check(h.list(n,limit).state,'23514','bounded limit');for(const role of ['anon','service_role'])check(h.list(n,20,n.member_id,role).state,'42501','authenticated only');check(h.list(n,20,null).state,'42501','no member identity denied');check(h.list(n,20,'00000000-0000-4000-8000-000000000000').state,'42501','nonmember denied');
 for(const isolation of ['REPEATABLE READ','SERIALIZABLE']){assert.throws(()=>c.target(`BEGIN ISOLATION LEVEL ${isolation}; SELECT set_config('request.jwt.claim.sub','${n.member_id}',true); SET LOCAL ROLE authenticated; SELECT * FROM public.discover_masked_offers_for_my_need('${n.movement_need_id}',20);`),/25000/);checks++;}
 for(const scenario of ['withdrawn','full','access','intent','match','route','status']){
  const updates={withdrawn:`UPDATE private.offering_movement_availability SET status='withdrawn' WHERE id='${fresh.availability_id}'`,full:`UPDATE private.offering_movement_availability SET status='full',remaining_places=0 WHERE id='${fresh.availability_id}'`,access:`UPDATE public.member_vehicle_access SET active=false WHERE vehicle_id='${fresh.vehicle_id}'`,intent:`UPDATE private.offering_movement_intents SET status='withdrawn' WHERE id='${fresh.intent_id}'`,match:`UPDATE private.trusted_route_match_evidence SET status='superseded' WHERE id=(SELECT route_match_evidence_id FROM private.movement_offer_route_match_bindings WHERE movement_offer_id='${fo}')`,route:`UPDATE private.offering_route_evidence SET status='superseded' WHERE id='${fresh.route_id}'`,status:`UPDATE public.movement_offers SET status='withdrawn' WHERE id='${fo}'`};
  // Use one transaction/connection for mutation and rollback, keeping all live guards.
  const result=c.target(`BEGIN; ${updates[scenario]}; SELECT ${c.inboxSchema}.inbox_as('authenticated','${n.member_id}','SELECT * FROM public.discover_masked_offers_for_my_need(''${n.movement_need_id}'',20)'); ROLLBACK;`);const parsed=JSON.parse(result.split('\n').filter(l=>l.startsWith('{')).at(-1));check(parsed.ok,true,'invalid '+scenario+' skipped normally');check(parsed.rows.some(x=>x.movement_offer_id===fo),false,'invalid '+scenario+' excluded');
 }
 const restoreExpiry=h.instrument('private.assert_offering_movement_availability(uuid)',"clock_timestamp()+interval '2 hours'");try{check(h.list(n).rows,[],'expired availability support never ranks');}finally{restoreExpiry();}
 const tieNeed=h.requester(),a=h.offering(1),b=h.offering(4),stamp=c.target('SELECT clock_timestamp();'),one=h.offer(tieNeed,a,{stamp}),two=h.offer(tieNeed,b,{stamp});check(h.list(tieNeed).rows.map(x=>x.movement_offer_id),[one,two].sort(),'score/time ties use stable UUID; extra seats do not rank');
 const oldDef=c.target("SELECT pg_get_functiondef('public.discover_masked_offers_for_my_need(uuid,integer)'::regprocedure);");try{c.target(oldDef.replace('clock_timestamp()',"'"+stamp+"'::timestamptz-interval '1 minute'"));check(h.list(tieNeed).rows.map(x=>x.movement_offer_id),[one,two].sort(),'regressed live sample keeps historical offers valid');}finally{c.target(oldDef);}
 for(const column of ['rating','completed_movements']){assert.throws(()=>c.target(`UPDATE public.members SET ${column}=${column==='rating'?5:99} WHERE id='${fresh.member_id}';`),/23514/);checks++;}
 // Unexpected assertion failures must escape, never be converted into skipped rows.
 const assertion=c.target("SELECT pg_get_functiondef('private.assert_movement_offer_availability_binding(uuid)'::regprocedure);");
 for(const [state,message] of [['23514','unexpected invariant failure'],['P0002','query returned no rows'],['23514','Movement offer availability binding does not match'],['23514','Trusted route-match evidence does not match trusted matching context'],['23514','Availability trusted movement binding does not match'],['23514','Offering intent location owner or expiry does not match'],['23514','Offering route evidence is not eligible for matching'],['23514','Offering route evidence intent is not eligible'],['23514','Offering route evidence requires resolved eligible endpoints'],['XX000','programmer error'],['40P01','deadlock'],['57014','cancelled'],['P0001','unexpected exception'],['42501','unexpected authorization error']]){try{const replacement=assertion.replace(/AS (\$\w*\$)[^]*?\1/,`AS $test$ BEGIN RAISE EXCEPTION USING ERRCODE='${state}',MESSAGE='${message}'; END; $test$`);c.target(replacement);if(state==='57014'){assert.throws(()=>h.list(n),/57014/);checks++;}else {const result=h.list(n);check(result.ok,false,'unexpected errors never return normal rows '+message);check(result.state,state,'unexpected errors propagate '+state);check(result.message,message,'unexpected message unchanged '+message);}}finally{c.target(assertion);}}
 console.log('PASS '+checks+' PostgreSQL requester priority assertions');
 });}
if(require.main===module)main().catch(e=>{console.error(e.stack);process.exitCode=1;});module.exports={main};
