import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createActivationPaymentHandler, unavailablePaymentProvider} from '../functions/_shared/activation-payment.ts';
import {createPaymentBackend} from '../functions/_shared/payment-runtime.ts';
const need='11111111-1111-4111-8111-111111111111', viewer='22222222-2222-4222-8222-222222222222', alignment='33333333-3333-4333-8333-333333333333', payment='44444444-4444-4444-8444-444444444444';
const req=(body={movementNeedId:need},auth='Bearer user')=>new Request('https://edge.invalid/create-activation-payment',{method:'POST',headers:{'Content-Type':'application/json',...(auth?{Authorization:auth}:{})},body:JSON.stringify(body)});
function setup(options={}) {
 const calls=[];
 const db={authenticate:async(jwt)=>{calls.push('auth');assert.equal(jwt,'user');return options.invalid?null:viewer;},resolveOfferingAlignment:async(n,v)=>{calls.push('resolve');assert.equal(n,need);assert.equal(v,viewer);return options.rows??[{id:alignment,offering_member_id:viewer,status:'awaiting_activation_payment',activation_fee_minor:500,activation_currency:'NGN',...options.row}];},rpc:async(name,args)=>{calls.push('db');assert.equal(name,'create_alignment_activation_payment');assert.deepEqual(args,{p_alignment_id:alignment,p_amount_minor:500,p_currency:'NGN',p_provider:'test'});if(options.fail)throw Error('private readiness error');await options.wait;calls.push('committed');return [{payment_id:payment,alignment_id:alignment,payment_status:'pending',amount_minor:400,currency:'NGN'}];}};
 const provider={name:'test',isAvailable:()=>true,verifyCallback:async()=>null,initiate:async(p)=>{calls.push('provider');assert.deepEqual(p,{paymentId:payment,amountMinor:400,currency:'NGN'});if(options.providerFail)throw Error('secret reference');return {success:true};}};
 return {calls,handler:createActivationPaymentHandler(db,options.default?undefined:provider)};
}
for(const [label,auth,invalid] of [['missing',null,false],['invalid','Bearer user',true]])test(`${label} JWT denied`,async()=>{const h=setup({invalid});assert.equal((await h.handler(req(undefined,auth))).status,401);assert(!h.calls.includes('db'));});
for(const key of ['memberId','alignmentId','offeringMemberId','primaryRequesterId','amount','currency','provider','providerReference','paymentStatus','allParticipantsReady','faceReady','success','verified'])test(`rejects client ${key}`,async()=>{const h=setup();assert.equal((await h.handler(req({movementNeedId:need,[key]:true}))).status,400);assert.deepEqual(h.calls,[]);});
for(const value of ['bad',null,[],{},42])test(`rejects malformed movement ${JSON.stringify(value)}`,async()=>{const h=setup();assert.equal((await h.handler(req({movementNeedId:value}))).status,400);assert.deepEqual(h.calls,[]);});
test('unrelated or traveller cannot initiate',async()=>{for(const rows of [[],[{id:alignment,offering_member_id:need}], [{id:alignment},{id:alignment}]]){const h=setup({rows});assert.equal((await h.handler(req())).status,404);assert(!h.calls.includes('db'));}});
test('default unavailable creates no unusable ledger and contacts no provider',async()=>{const h=setup({default:true});assert.deepEqual(await(await h.handler(req())).json(),{state:'payment_provider_unavailable'});assert.deepEqual(h.calls,['auth','resolve']);});
test('missing trusted fee fails closed',async()=>{const h=setup({row:{activation_fee_minor:null}});assert.equal((await h.handler(req())).status,503);assert(!h.calls.includes('db'));});
test('DB readiness rejection never contacts provider and hides details',async()=>{const h=setup({fail:true});assert.deepEqual(await(await h.handler(req())).json(),{state:'activation_not_ready'});assert(!h.calls.includes('provider'));});
test('provider waits for committed authoritative response',async()=>{let release;const wait=new Promise(r=>release=r);const h=setup({wait});const response=h.handler(req());await new Promise(r=>setImmediate(r));assert(!h.calls.includes('provider'));release();const r=await response;assert.deepEqual(h.calls,['auth','resolve','db','committed','provider']);assert.deepEqual(await r.json(),{state:'payment_pending'});assert.equal(r.headers.get('Cache-Control'),'private, no-store');});
test('repeat requests reuse DB payment identity; provider result never activates',async()=>{const h=setup();for(let i=0;i<2;i++)assert.deepEqual(await(await h.handler(req())).json(),{state:'payment_pending'});assert.equal(h.calls.filter(x=>x==='provider').length,2);});
test('provider failure hides internal errors',async()=>{const h=setup({providerFail:true});assert.deepEqual(await(await h.handler(req())).json(),{state:'payment_provider_unavailable'});});
test('only activated database state returns activated',async()=>{const h=setup({row:{status:'activated',activated_at:'2026-01-01T00:00:00Z'}});assert.deepEqual(await(await h.handler(req())).json(),{state:'activated'});assert(!h.calls.includes('db'));});
test('activated without activation evidence fails closed',async()=>{const h=setup({row:{status:'activated'}});assert.deepEqual(await(await h.handler(req())).json(),{state:'activation_not_ready'});});
test('default callback rejects ordinary JWT and success boolean',async()=>{assert.equal(await unavailablePaymentProvider.verifyCallback(new TextEncoder().encode('{"success":true}'),new Headers({Authorization:'Bearer user'}),new AbortController().signal),null);await assert.rejects(()=>unavailablePaymentProvider.initiate({},new AbortController().signal));});
test('production has no fake toggle or payment callback mutation',()=>{const entry=fs.readFileSync('supabase/functions/create-activation-payment/index.ts','utf8');assert.match(entry,/createActivationPaymentHandler\(runtimePaymentBackend\(\)\)/);assert.doesNotMatch(entry.replace(/\/\/[^\n]*/g,''),/env|fake|mark_alignment_activation_payment_succeeded/);});
test('runtime lookup uses service credentials and verified payer filters privately',async()=>{let called;const db=createPaymentBackend('https://project.invalid','server-secret',async(url,opts)=>{called={url,opts};return Response.json([]);});await db.resolveOfferingAlignment(need,viewer,new AbortController().signal);const q=new URL(called.url).searchParams;assert.equal(q.get('movement_need_id'),`eq.${need}`);assert.equal(q.get('offering_member_id'),`eq.${viewer}`);assert.equal(q.get('limit'),'2');assert.equal(called.opts.headers.apikey,'server-secret');assert.equal(called.opts.redirect,'error');});
test('existing database gates and idempotency remain present',()=>{const sql=fs.readFileSync('supabase/migrations/0016_secure_profile_photo_submissions.sql','utf8');const old=fs.readFileSync('supabase/migrations/0007_activation_payment_foundation.sql','utf8');assert.match(sql,/assert_alignment_face_ready/);assert.match(sql,/create_alignment_activation_payment/);assert.match(old,/WHERE status = 'pending'/);assert.match(old,/WHERE status = 'succeeded'/);assert.match(old,/TO service_role/);});

for(const key of ['paymentSucceeded','successful'])test(`rejects additional client claim ${key}`,async()=>{const h=setup();assert.equal((await h.handler(req({movementNeedId:need,[key]:true}))).status,400);assert.deepEqual(h.calls,[]);});
test('concurrent requests still consult DB and use the same returned payment identity',async()=>{const h=setup();const responses=await Promise.all([h.handler(req()),h.handler(req())]);for(const r of responses)assert.deepEqual(await r.json(),{state:'payment_pending'});assert.equal(h.calls.filter(c=>c==='db').length,2);assert.equal(h.calls.filter(c=>c==='provider').length,2);});
test('external capture cannot bypass a later DB gate rejection',async()=>{const h=setup();assert.deepEqual(await(await h.handler(req())).json(),{state:'payment_pending'});assert(!h.calls.includes('mark_alignment_activation_payment_succeeded'));const sql=fs.readFileSync('supabase/migrations/0016_secure_profile_photo_submissions.sql','utf8');assert.match(sql,/PERFORM private\.assert_alignment_face_ready\(NEW\.id\)/);const doc=fs.readFileSync('docs/activation-payment.md','utf8');assert.match(doc,/PostgreSQL cannot undo that charge/);assert.match(doc,/refund\/reconciliation\/reverification/);});
test('auth transport verifies user JWT then separates service-only database credentials',async()=>{const calls=[];const db=createPaymentBackend('https://project.invalid','server-secret',async(url,opts)=>{calls.push({url,opts});return Response.json(url.endsWith('/auth/v1/user')?{id:viewer,role:'authenticated'}:[]);});assert.equal(await db.authenticate('user-jwt',new AbortController().signal),viewer);await db.rpc('create_alignment_activation_payment',{},new AbortController().signal);assert.equal(calls[0].opts.headers.Authorization,'Bearer user-jwt');assert.equal(calls[1].opts.headers.Authorization,'Bearer server-secret');assert.equal(calls[1].opts.headers.Prefer,undefined);});
