const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const sql=fs.readFileSync('supabase/migrations/0018_meeting_point_and_journey_start.sql','utf8');
const testSql=fs.readFileSync('supabase/tests/0018_meeting_point_and_journey_start_test.sql','utf8');
test('0018 transactional and never replaces installed start behavior',()=>{assert.match(sql,/^BEGIN;/);assert.match(sql,/COMMIT;\s*$/);assert.doesNotMatch(sql,/CREATE OR REPLACE|DISABLE TRIGGER|DISABLE ROW LEVEL SECURITY/);});
test('private text-only table has constraints and no client table grant',()=>{assert.match(sql,/journey_id uuid PRIMARY KEY REFERENCES public.journeys\(id\)/);assert.match(sql,/length\(place_text\) BETWEEN 1 AND 200/);assert.match(sql,/revision bigint NOT NULL CHECK \(revision >= 1\)/);assert.match(sql,/REVOKE ALL ON private.journey_meeting_points FROM PUBLIC, anon, authenticated/);assert.doesNotMatch(sql,/latitude|longitude|geofence/);});
test('existing successful-payment and actual confirmed participant helper remains authority',()=>{assert.match(sql,/private.post_activation_reveal_subjects\(p_need,auth.uid\(\)\)/);const original=fs.readFileSync('supabase/migrations/0014_secure_post_activation_reveal.sql','utf8');assert.match(original,/ap.status = 'succeeded'/);assert.match(original,/mp.status = 'confirmed'/);});
test('all functions have fixed search path and client-facing explicit ACLs',()=>{const functions=[...sql.matchAll(/CREATE FUNCTION ([\w.]+)\(/g)].map(m=>m[1]);assert.equal(functions.length,6);assert.equal((sql.match(/SECURITY DEFINER SET search_path = ''/g)||[]).length,6);for(const name of functions){assert(sql.includes('REVOKE ALL ON FUNCTION '+name));if(name.startsWith('public.'))assert(sql.includes('GRANT EXECUTE ON FUNCTION '+name));}});
test('new mutations lock journey then alignment before revision and freeze checks',()=>{assert(sql.indexOf('WHERE j.id=selected_id FOR UPDATE')<sql.indexOf('WHERE a.id=selected_alignment FOR UPDATE'));assert.match(sql,/p_expected_revision IS DISTINCT FROM current_revision/);assert.match(sql,/revision=mp.revision\+1/);assert.match(sql,/c.requested_at IS NOT NULL THEN/);});
test('request and confirm delegate original authority and legacy start has required-point trigger',()=>{assert.match(sql,/PERFORM \* FROM public.request_journey_start\(c.journey_id\)/);assert.match(sql,/PERFORM \* FROM public.confirm_journey_start\(c.journey_id\)/);assert.match(sql,/auth.uid\(\)<>c.offering_id/);assert.match(sql,/auth.uid\(\)<>c.requester_id/);assert.match(sql,/BEFORE UPDATE OF start_requested_at ON public.journeys/);assert.match(sql,/OLD.start_requested_at IS NULL AND NEW.start_requested_at IS NOT NULL/);});
test('preflight stops legacy pending handshakes without changing data',()=>{const preflight=sql.slice(0,sql.indexOf('CREATE TABLE'));assert.match(preflight,/resolve legacy pending journey-start requests/);assert.doesNotMatch(preflight,/UPDATE public|DELETE FROM/);});
test('safe RPC tables expose exactly eight fields and no internal ids',()=>{const tables=[...sql.matchAll(/CREATE FUNCTION public\.[\s\S]*?RETURNS TABLE \(([\s\S]*?)\)/g)];assert.equal(tables.length,4);for(const m of tables){const names=m[1].split(',').map(x=>x.trim().split(/\s/)[0]);assert.deepEqual(names,['meeting_point_text','meeting_point_revision','journey_state','start_requested_at','started_at','can_edit_meeting_point','can_request_start','can_confirm_start']);}});
test('rollback test uses invoker JWT/role harness and actual start/payment RPCs',()=>{assert.match(testSql,/^BEGIN;/);assert.match(testSql,/ROLLBACK;\s*$/);assert.match(testSql,/SECURITY INVOKER/);assert.match(testSql,/mark_alignment_activation_payment_succeeded/);assert.match(testSql,/complete_face_verification_callback_for_server/);assert.doesNotMatch(testSql,/DISABLE TRIGGER|CREATE OR REPLACE FUNCTION public|GRANT .* TO authenticated/);});
test('rollback exercises revisions, nonparticipants, freeze and idempotent confirmation',()=>{for(const phrase of ['stale revision rejected','blank text rejected','excessive text rejected','extra traveller cannot edit','legacy start cannot bypass','request freezes without starting','repeat request idempotent','repeat confirm idempotent','frozen edit denied','exact safe result keys'])assert(testSql.includes(phrase));});

test('stored point validity is checked by both capabilities, both wrappers and legacy trigger',()=>{assert.equal((sql.match(/mp\.place_text=btrim\(mp\.place_text\) AND length\(mp\.place_text\) BETWEEN 1 AND 200 AND mp\.place_text ~ '\[\^\[:space:\]\]'/g)||[]).length,5);assert.equal((sql.match(/coalesce\(\(mp\.place_text=/g)||[]).length,2);});
test('preflight and write-blocking table lock precede all schema mutations',()=>{const lock=sql.indexOf('LOCK TABLE public.journeys IN SHARE ROW EXCLUSIVE MODE');const pre=sql.indexOf('IF EXISTS (SELECT 1 FROM public.journeys');const create=sql.indexOf('CREATE TABLE');assert(lock>0&&lock<pre&&pre<create);assert(!sql.slice(0,create).includes('COMMIT;'));});
test('all mutation paths acquire shared journey-lock helper before decision or delegation',()=>{for(const name of ['set_my_movement_meeting_point','request_my_movement_start','confirm_my_movement_start']){const start=sql.indexOf('CREATE FUNCTION public.'+name);const body=sql.slice(start,sql.indexOf('$$;',start));const lock=body.indexOf('private.movement_coordination_context(p_movement_need_id,true)');assert(lock>0);assert(lock<body.indexOf('IF NOT FOUND'));assert(!/COMMIT|ROLLBACK/.test(body));}const helper=sql.slice(sql.indexOf('CREATE FUNCTION private.movement_coordination_context'),sql.indexOf('CREATE FUNCTION public.get_my_movement_coordination_status'));assert(helper.indexOf('RETURN QUERY')>helper.indexOf('FOR UPDATE'));assert.match(helper,/RETURN QUERY[\s\S]*private.post_activation_reveal_subjects/);});
test('client RPC exact signatures revoked from public/anon and granted to authenticated only',()=>{for(const sig of ['get_my_movement_coordination_status(uuid)','set_my_movement_meeting_point(uuid,text,bigint)','request_my_movement_start(uuid)','confirm_my_movement_start(uuid)']){assert(sql.includes('REVOKE ALL ON FUNCTION public.'+sig+' FROM PUBLIC,anon;'));assert(sql.includes('GRANT EXECUTE ON FUNCTION public.'+sig+' TO authenticated;'));}assert.doesNotMatch(sql,/EXECUTE\s+format|EXECUTE\s+['"`]/);});
test('new rollback cases exercise first revision and applied-request replay, not only string inspection',()=>{for(const phrase of ['first creation rejects zero expected revision','replayed first creation cannot create another revision','replayed update cannot increment again','stored invalid text rejected','exact four client signatures and no alternate overloads','no public execute on new functions'])assert(testSql.includes(phrase));assert.match(testSql,/EXCEPTION WHEN check_violation/);});
