'use strict';
const fs=require('fs');
const path=require('path');
const p=path.join(process.cwd(),'supabase','migrations','0025_trusted_route_producer_boundary.sql');
const raw=fs.readFileSync(p,'utf8');
const stripComments=s=>s.replace(/'(?:''|[^'])*'|--[^\r\n]*|\/\*[\s\S]*?\*\//g,t=>t.startsWith("'")?t:' ');
const sql=stripComments(raw);
const writer=sql.slice(sql.indexOf('CREATE OR REPLACE FUNCTION public.record_offering_route_evidence_for_server'));
const validator=sql.slice(0,sql.indexOf('CREATE OR REPLACE FUNCTION public.record_offering_route_evidence_for_server'));
const live=stripComments(fs.readFileSync(path.join(process.cwd(),'supabase','tests','0025_trusted_route_producer_boundary_test.sql'),'utf8'));
const checks=[];
const c=(name,ok)=>checks.push({name,passed:!!ok});
c('transaction wrapper',/^\s*BEGIN;/i.test(sql)&&/COMMIT;\s*$/i.test(sql));
c('one server route writer',(sql.match(/CREATE\s+OR\s+REPLACE\s+FUNCTION\s+public\.record_offering_route_evidence_for_server/gi)||[]).length===1);
c('security definer',/SECURITY\s+DEFINER/i.test(writer));
c('empty search path',/SET\s+search_path\s*=\s*''/i.test(writer));
c('service-only execute',/GRANT\s+EXECUTE[^;]+TO\s+service_role\s*;/i.test(writer)&&/REVOKE\s+ALL[^;]+FROM\s+PUBLIC,anon,authenticated,service_role\s*;/i.test(writer)&&(sql.match(/\bGRANT\b/gi)||[]).length===1);
c('no route-table mutation grant',!/GRANT\s+(?:ALL|INSERT|UPDATE|DELETE)[\s\S]*private\.offering_route_evidence/i.test(sql));
c('caller cannot submit offering member',!/p_offering_member_id/i.test(sql));
c('caller cannot submit origin binding',!/p_origin_location_reference_id/i.test(sql));
c('caller cannot submit destination binding',!/p_destination_location_reference_id/i.test(sql));
c('database derives version',/COALESCE\(MAX\(e\.version\),0\)\+1/i.test(sql));
c('supersedes current history',/SET\s+status='superseded'/i.test(sql));
c('reuses shape validator',/assert_geojson_linestring_v1\(p_route_shape\)/i.test(sql));
c('reuses full evidence validator',/assert_offering_route_evidence\(v_new_id\)/i.test(sql));
c('provider replay mismatch fails closed',/Provider route reference does not match recorded evidence/i.test(sql));
c('no vendor hardwired',!/google|mapbox|valhalla|osrm|https?:\/\//i.test(sql));
c('forward validator replacement',/CREATE OR REPLACE FUNCTION private\.assert_geojson_linestring_v1\(p_shape jsonb\)/.test(validator));
c('validator security and private ACL',/SECURITY DEFINER\s+SET search_path = ''/.test(validator)&&/REVOKE ALL ON FUNCTION private\.assert_geojson_linestring_v1\(jsonb\)\s+FROM PUBLIC,anon,authenticated,service_role;/.test(validator));
c('null-safe object guard precedes field operations',/IF jsonb_typeof\(p_shape\) IS DISTINCT FROM 'object' THEN[^]*?END IF;\s+IF p_shape->>'type'/.test(validator));
c('null-safe required fields',/p_shape->>'type' IS DISTINCT FROM 'LineString'/.test(validator)&&/jsonb_typeof\(p_shape->'coordinates'\) IS DISTINCT FROM 'array'/.test(validator));
c('extra keys and minimum points rejected',/\(p_shape - 'type' - 'coordinates'\) IS DISTINCT FROM '\{\}'::jsonb/.test(validator)&&/jsonb_array_length\(p_shape->'coordinates'\) < 2/.test(validator));
c('point type guard precedes array length',/IF jsonb_typeof\(point\) IS DISTINCT FROM 'array' THEN[^]*?END IF;\s+IF jsonb_array_length\(point\) <> 2/.test(validator));
c('both coordinates must be JSON numbers',[0,1].every(i=>validator.includes(`jsonb_typeof(point->${i}) IS DISTINCT FROM 'number'`)));
c('longitude and latitude bounds retained',/longitude_value < -180 OR longitude_value > 180\s+OR latitude_value < -90 OR latitude_value > 90/.test(validator));
c('fresh clock after intent lock',/FOR UPDATE;\s+IF NOT FOUND THEN[^]*?END IF;\s+v_now := clock_timestamp\(\);\s+IF v_intent.status/.test(writer));
c('fresh clock after endpoint locks',/WHERE lr.id=v_destination_id FOR SHARE;\s+v_now := clock_timestamp\(\);/.test(writer));
c('fresh clock after provider reference lock',/FOR UPDATE;\s+IF FOUND THEN\s+v_now := clock_timestamp\(\);/.test(writer));
c('no statement-start eligibility clock',!/statement_timestamp\(/i.test(writer));
c('retry authoritative validation immediately before return',/PERFORM private\.assert_offering_route_evidence\(v_existing.id\);\s+RETURN QUERY SELECT v_existing.id/.test(writer));
c('flush specific constraint after explicit validation',/PERFORM private\.assert_offering_route_evidence\(v_new_id\);\s+SET CONSTRAINTS private\.offering_route_evidence_complete IMMEDIATE;\s+SET CONSTRAINTS private\.offering_route_evidence_complete DEFERRED;/.test(writer));
c('no trigger removal or global constraint changes',!/SET CONSTRAINTS ALL|DISABLE TRIGGER|DROP TRIGGER|DELETE FROM|TRUNCATE/i.test(sql));
c('behavioral test uses distinct dollar tags',/DO \$route_test\$/.test(live)&&/\$route_test\$;/.test(live)&&/\$sql\$SELECT/.test(live)&&!live.includes('$$'));
c('behavioral test covers missing fields', ['empty object','missing type','missing coordinates','normalized linestring'].every(label=>live.includes(label)));
c('behavioral test covers superseded replay',live.includes('15 superseded reference replay rejected'));
c('behavioral test flushes before results',/SET CONSTRAINTS private\.offering_route_evidence_complete IMMEDIATE;[^]*?\$route_test\$;\s+SELECT count\(\*\)/.test(live));
const failed=checks.filter(x=>!x.passed);
checks.forEach(x=>console.log(`${x.passed?'PASS':'FAIL'}  ${x.name}`));
console.log(`\n${checks.length} tests, ${checks.length-failed.length} passed, ${failed.length} failed`);
if(failed.length)process.exit(1);
