const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
function load(file,extra={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,Error,TypeError,AbortController,setTimeout,clearTimeout,...extra});return exports;}
const {createActivationPaymentController:create,paymentCopy}=load('src/state/activationPaymentState.ts');
const need='11111111-1111-4111-8111-111111111111';
function deferred(){let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};}
function service(response,error){const calls=[];const api=load('src/services/activationPaymentService.ts',{require:()=>({supabase:{auth:{getSession:async()=>({data:{session:{access_token:'user'}}})}}}),process:{env:{EXPO_PUBLIC_SUPABASE_URL:'https://project.invalid',EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY:'public'}},fetch:async(url,opts)=>{calls.push({url,opts});if(error)throw error;return response;}});return {api,calls};}
test('service sends only movementNeedId with normal JWT',async()=>{const h=service(Response.json({state:'payment_pending'}));assert.equal(await h.api.requestActivationPayment(need),'payment_pending');assert.deepEqual(JSON.parse(h.calls[0].opts.body),{movementNeedId:need});assert.equal(h.calls[0].opts.headers.Authorization,'Bearer user');assert.equal(h.calls[0].opts.redirect,'error');});
test('bad movement rejected before request',async()=>{const h=service();await assert.rejects(()=>h.api.requestActivationPayment('bad'));assert.equal(h.calls.length,0);});
for(const [code,state] of [[200,'activated'],[503,'payment_provider_unavailable'],[409,'activation_not_ready'],[200,'payment_pending']])test(`safe backend state ${state}`,async()=>{const h=service(Response.json({state},{status:code}));assert.equal(await h.api.requestActivationPayment(need),state);});
test('extra private fields rejected',async()=>{const h=service(Response.json({state:'activated',alignmentId:need}));await assert.rejects(()=>h.api.requestActivationPayment(need),/payment_unavailable/);});
test('failed HTTP response cannot assert activated',async()=>{const h=service(Response.json({state:'activated'},{status:503}));await assert.rejects(()=>h.api.requestActivationPayment(need),/payment_unavailable/);});
test('network is distinct from payment failure',async()=>{const h=service(null,new TypeError('fetch failed'));await assert.rejects(()=>h.api.requestActivationPayment(need),/network_unavailable/);});
test('authentication stays safe',async()=>{const h=service(new Response('secret',{status:401}));await assert.rejects(()=>h.api.requestActivationPayment(need),/authentication_required/);});
test('duplicate taps blocked',async()=>{const d=deferred();let calls=0;const states=[];const c=create(need,async()=>{calls++;return d.promise;},s=>states.push(s));const p=c.start();await c.start();assert.equal(calls,1);d.resolve('payment_pending');await p;assert.deepEqual(states,['preparing_activation','payment_pending']);});
test('cancelled stale activation cannot overwrite newer attempt',async()=>{const d=deferred();let n=0;const states=[];const c=create(need,async()=>++n===1?d.promise:'activation_not_ready',s=>states.push(s));const p=c.start();c.cancel();await c.start();d.resolve('activated');await p;assert.equal(states.at(-1),'activation_not_ready');assert(!states.includes('activated'));});
test('unmounted owner ignores activation and cannot restart',async()=>{const d=deferred();const states=[];const c=create(need,()=>d.promise,s=>states.push(s));const p=c.start();c.dispose();d.resolve('activated');await p;await c.start();assert.deepEqual(states,['preparing_activation']);});
test('errors retry and never leak raw errors',async()=>{let n=0;const states=[];const c=create(need,async()=>{if(++n===1)throw Error('private SQL');return 'payment_pending';},s=>states.push(s));await c.start();assert.equal(states.at(-1),'payment_unavailable');await c.start();assert.equal(states.at(-1),'payment_pending');});
test('copy makes no group readiness or payment success claims',()=>{assert.equal(paymentCopy.activation_not_ready,'Activation is not ready yet.');assert.equal(paymentCopy.activated,'Movement activated.');for(const [key,value] of Object.entries(paymentCopy)){assert.doesNotMatch(value,/everyone|all participants|verified|approved|succeeded/i);if(key!=='activated')assert.doesNotMatch(value,/activated/i);}});
test('controller rejects invalid movement without request',async()=>{let called=false;const c=create('bad',async()=>{called=true;return 'activated';},()=>{});await c.start();assert.equal(called,false);});

test('controller rejects coercible non-string movement input',async()=>{for(const input of [[need],{toString:()=>need}]){let called=false;const states=[];await create(input,async()=>{called=true;return 'activated';},s=>states.push(s)).start();assert.equal(called,false);assert.deepEqual(states,['activation_not_ready']);}});
test('face success and provider objects cannot manufacture payment state',async()=>{for(const result of [{success:true},{state:'activated'},{status:'succeeded',readyForActivation:true},true,'succeeded','payment_succeeded']){const states=[];await create(need,async()=>result,s=>states.push(s)).start();assert.deepEqual(states,['preparing_activation','payment_unavailable']);}});
test('retry after provider unavailable makes a fresh backend request',async()=>{let count=0;const states=[];const c=create(need,async()=>++count===1?'payment_provider_unavailable':'activation_not_ready',s=>states.push(s));await c.start();await c.start();assert.equal(count,2);assert.equal(states.at(-1),'activation_not_ready');});
test('service cancellation rejects late backend activation',async()=>{const abort=new AbortController();const h=service({status:200,redirected:false,json:async()=>{abort.abort();return {state:'activated'};}});await assert.rejects(()=>h.api.requestActivationPayment(need,abort.signal),/network_unavailable/);});
