const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const path=require('node:path');
const need='11111111-1111-4111-8111-111111111111';
function loader(stubs){function load(p){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,Error,AbortController,require(n){if(n in stubs)return stubs[n];if(n.startsWith('.'))return load(path.resolve(path.dirname(p),n)+'.ts');return require(n);}});return exports;}return load;}
function text(e){if(e==null)return '';if(typeof e==='string')return e;if(Array.isArray(e))return e.map(text).join(' ');if(typeof e.type==='function')return text(e.type(e.props));return text(e.props?.children);}
function buttons(e){if(!e||typeof e!=='object')return [];if(Array.isArray(e))return e.flatMap(buttons);return [...(e.type==='Pressable'?[e]:[]),...buttons(e.props?.children)];}
function card(state,start=async()=>{},onContinueJourney){return loader({'react-native':{View:'View',Text:'Text',Pressable:'Pressable'},'../hooks/useActivationPayment':{useActivationPayment:id=>{assert.equal(id,need);return {state,signedIn:true,active:true,start};}}})('src/components/ActivationPaymentCard.tsx').ActivationPaymentCard({movementNeedId:need,onContinueJourney});}
for(const state of ['idle','preparing_activation','activation_not_ready','payment_provider_unavailable','payment_pending','network_unavailable','payment_unavailable','activated'])test(`safe UI ${state}`,()=>{const e=card(state);const t=text(e);assert.doesNotMatch(t,/11111111|alignment|NGN|\u20a6|everyone|all participants verified|payment failed/i);assert.equal(t.includes('Movement activated.'),state==='activated');if(state==='activation_not_ready')assert(t.includes('Activation is not ready yet.'));if(state==='payment_provider_unavailable')assert(t.includes('not available in this build'));});
test('button calls only the bound service action',async()=>{let calls=0;const e=card('idle',async(...args)=>{assert.equal(args.length,0);calls++;});buttons(e)[0].props.onPress();assert.equal(calls,1);});
test('preparing disables taps; journey seam requires backend activated',()=>{assert.equal(buttons(card('preparing_activation'))[0].props.disabled,true);let count=0;for(const state of ['idle','payment_pending','payment_provider_unavailable'])assert(!text(card(state,undefined,()=>count++)).includes('Continue to journey'));buttons(card('activated',undefined,()=>count++))[0].props.onPress();assert.equal(count,1);});
function harness(request){let auth,app,cleanup;let snapshot;const AppState={currentState:'active',addEventListener:(_,fn)=>{app=fn;return {remove(){}};}};const use=loader({react:{useMemo:fn=>fn(),useCallback:fn=>fn,useSyncExternalStore:(_s,get)=>{snapshot=get;return get();}},'expo-router':{useFocusEffect:fn=>{cleanup=fn();}},'react-native':{AppState},'../lib/supabase':{supabase:{auth:{onAuthStateChange:fn=>{auth=fn;return {data:{subscription:{unsubscribe(){}}}};}}}},'../services/activationPaymentService':{requestActivationPayment:request}})('src/hooks/useActivationPayment.ts').useActivationPayment;const model=use(need);return {model,state:()=>snapshot(),login(id='member'){auth('SIGNED_IN',{user:{id}});},background(){AppState.currentState='background';app();},cleanup:()=>cleanup()};}
function deferred(){let resolve;return {promise:new Promise(r=>resolve=r),resolve:v=>resolve(v)};}
test('hook makes no automatic request; taps use only need and abort signal',async()=>{let calls=0;const h=harness(async(id,signal)=>{calls++;assert.equal(id,need);assert(signal instanceof AbortSignal);return 'payment_provider_unavailable';});h.login();assert.equal(calls,0);await h.model.start();assert.equal(h.state().state,'payment_provider_unavailable');h.cleanup();});
for(const reason of ['background','cleanup','account'])test(`${reason} drops late activated result`,async()=>{const d=deferred();let signal;const h=harness(async(_id,s)=>{signal=s;return d.promise;});h.login();const p=h.model.start();if(reason==='account')h.login('new-member');else h[reason]();assert(signal.aborted);d.resolve('activated');await p;assert.equal(h.state().state,'idle');});
test('duplicate taps and retry remain backend authoritative',async()=>{const d=deferred();let count=0;const h=harness(async()=>++count===1?d.promise:'activation_not_ready');h.login();const p=h.model.start();await h.model.start();assert.equal(count,1);d.resolve('payment_provider_unavailable');await p;await h.model.start();assert.equal(h.state().state,'activation_not_ready');h.cleanup();});
