const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');const path=require('node:path');
const need='11111111-1111-4111-8111-111111111111';
function loader(stubs,globals={}){function load(p){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,Error,Date,AbortController,setTimeout,clearTimeout,...globals,require(n){if(n in stubs)return stubs[n];if(n.startsWith('.'))return load(path.resolve(path.dirname(p),n)+'.ts');return require(n);}});return exports;}return load;}
const person=(role='offering_member')=>({personNumber:1,personRole:role,firstName:'Ada',age:30,verified:true,rating:4.5,completedMovements:2,profilePhotoToken:null,profilePhotoExpiresAt:null});
function service(rows=[person()],vehicle={vehicleDisplayName:'Blue Lexus RX350',plateNumber:'ABC123'},photo=async()=>null,globals={}){const calls=[];const api=loader({'./movementService':{getPostActivationPeople:async id=>{calls.push(['people',id]);return rows;},getPostActivationVehicle:async id=>{calls.push(['vehicle',id]);return vehicle;}},'./profilePhotoService':{getPostActivationProfilePhoto:async token=>{calls.push(['photo',token]);return photo();}}},globals)('src/services/coordinationService.ts');return {calls,api};}
for(const value of ['bad',null,[need],{movementNeedId:need}])test(`invalid input ${JSON.stringify(value)} skips RPCs`,async()=>{const h=service();assert.equal(await h.api.loadMovementCoordination(value,new AbortController().signal),null);assert.equal(h.calls.length,0);});
test('empty unauthorized/nonactivated reveal hides even a vehicle response',async()=>{const h=service([]);assert.equal(await h.api.loadMovementCoordination(need,new AbortController().signal),null);assert.equal(h.calls.length,1);});
test('traveller sees only backend offering member and authorized natural vehicle/plate',async()=>{const h=service();const r=await h.api.loadMovementCoordination(need,new AbortController().signal);assert.equal(r.people.length,1);assert.equal(r.people[0].personRole,'offering_member');assert.equal(r.vehicle.plateNumber,'ABC123');assert.equal(r.vehicle.vehicleDisplayName,'Blue Lexus RX350');});
test('offering member sees returned primary and invited travellers without redundant own vehicle',async()=>{const h=service([person('primary_requester'),{...person('invited_participant'),personNumber:2}]);const r=await h.api.loadMovementCoordination(need,new AbortController().signal);assert.equal(r.people.length,2);assert.equal(r.vehicle,null);assert.equal(h.calls.length,1);});
for(const role of ['declined','removed','invited','unconfirmed'])test(`unknown role ${role} fails closed`,async()=>{const h=service([person(role)]);await assert.rejects(()=>h.api.loadMovementCoordination(need,new AbortController().signal));});
test('mixed traveller direction fails closed',async()=>{await assert.rejects(()=>service([person(),person('invited_participant')]).api.loadMovementCoordination(need,new AbortController().signal));});
test('projection excludes private fields and missing ratings are not fabricated',async()=>{const p={...person(),rating:null,firstName:null,memberId:'secret',commonMovementArea:'secret',phone:'secret',email:'secret',dateOfBirth:'secret',storagePath:'secret'};const h=service([p],{vehicleDisplayName:'Blue Lexus',plateNumber:'ABC123',year:2020,vehicleId:'secret'});const r=await h.api.loadMovementCoordination(need,new AbortController().signal);assert(!JSON.stringify(r).includes('secret'));assert(!JSON.stringify(r).includes('year'));assert.equal(r.people[0].rating,null);assert(!('profilePhotoToken' in r.people[0]));});
test('secure token delivers in-memory bytes without retaining token or storage URL',async()=>{const token='a'.repeat(64);const p={...person(),profilePhotoToken:token,profilePhotoExpiresAt:'2099-01-01T00:00:00Z'};class Reader{readAsDataURL(){this.result='data:image/png;base64,AQ==';this.onload();}abort(){}}const h=service([p],null,async()=>new Blob([new Uint8Array([1])],{type:'image/png'}),{FileReader:Reader});const r=await h.api.loadMovementCoordination(need,new AbortController().signal);assert.equal(r.people[0].photoUri,'data:image/png;base64,AQ==');assert.equal(h.calls[1][1],token);assert(!JSON.stringify(r).includes(token));});
test('expired photo token never requests image',async()=>{const h=service([{...person(),profilePhotoToken:'a'.repeat(64),profilePhotoExpiresAt:'2000-01-01T00:00:00Z'}]);const r=await h.api.loadMovementCoordination(need,new AbortController().signal);assert.equal(r.people[0].photoUri,null);assert(!h.calls.some(c=>c[0]==='photo'));});
function text(e){if(e==null)return '';if(typeof e==='string'||typeof e==='number')return String(e);if(Array.isArray(e))return e.map(text).join(' ');if(typeof e.type==='function')return text(e.type(e.props));return text(e.props?.children);}
function view(state){return loader({'./MeetingJourney':{MeetingJourney:()=>null},'react-native':{View:'View',Text:'Text',Pressable:'Pressable',Image:'Image'},'../hooks/useMovementCoordination':{useMovementCoordination:()=>({state,refresh:async()=>{}})}})('src/components/MovementCoordination.tsx').MovementCoordination({movementNeedId:need});}
for(const phase of ['unavailable','loading','error','signed_out'])test(`${phase} cannot render stale private reveal`,()=>{const t=text(view({phase,reveal:{people:[person()],vehicle:{vehicleDisplayName:'Blue Lexus',plateNumber:'SECRET'}}}));assert(!t.includes('Ada'));assert(!t.includes('SECRET'));assert(!t.includes('Movement activated'));});
test('ready view shows safe cards and truthful unavailable capabilities',()=>{const t=text(view({phase:'ready',reveal:{people:[{...person(),commonMovementArea:'SECRET',email:'SECRET',storagePath:'SECRET'}],vehicle:null}}));assert(t.includes('Ada'));assert.match(t,/Age:\s+30/);assert.match(t,/Rating:\s+4\.5/);assert(!t.includes('SECRET'));assert(t.includes('not available in this build'));});
function deferred(){let resolve,reject;return {promise:new Promise((a,b)=>{resolve=a;reject=b;}),resolve:v=>resolve(v),reject:e=>reject(e)};}
function harness(load){let auth,app,cleanup,snapshot;const timers=new Map();let timer=0;const AppState={currentState:'active',addEventListener:(_,fn)=>{app=fn;return {remove(){}};}};const hook=loader({react:{useMemo:fn=>fn(),useCallback:fn=>fn,useSyncExternalStore:(_sub,get)=>{snapshot=get;return get();}},'expo-router':{useFocusEffect:fn=>{cleanup=fn();}},'react-native':{AppState},'../lib/supabase':{supabase:{auth:{onAuthStateChange:fn=>{auth=fn;return {data:{subscription:{unsubscribe(){}}}};}}}},'../services/coordinationService':{loadMovementCoordination:load,validMovementNeed:v=>v===need}},{setTimeout:fn=>{timers.set(++timer,fn);return timer;},clearTimeout:id=>timers.delete(id)})('src/hooks/useMovementCoordination.ts').useMovementCoordination;const model=hook(need);return {model,state:()=>snapshot(),login:(id='a')=>auth('SIGNED_IN',{user:{id}}),background:()=>{AppState.currentState='background';app();},resume:()=>{AppState.currentState='active';app();},cleanup:()=>cleanup()};}
const flush=()=>new Promise(r=>setImmediate(r));
for(const action of ['background','cleanup','account'])test(`${action} clears reveal and rejects late identity`,async()=>{const d=deferred();let signal;const h=harness(async(_,s)=>{signal=s;return d.promise;});h.login();if(action==='account')h.login('b');else h[action]();d.resolve(null);await flush();assert.equal(h.state().reveal,null);h.cleanup();});
test('new refresh wins over stale old response and errors expose no SQL',async()=>{const d=deferred();let n=0;const h=harness(async()=>++n===1?d.promise:null);h.login();await h.model.refresh();d.resolve({people:[person()],vehicle:null});await flush();assert.equal(h.state().phase,'unavailable');h.cleanup();const e=harness(async()=>{throw Error('SECRET SQL');});e.login();await flush();assert.deepEqual(JSON.parse(JSON.stringify(e.state())),{phase:'error',reveal:null});e.cleanup();});
test('resume rechecks backend rather than restoring cached identity',async()=>{let count=0;const h=harness(async()=>{count++;return {people:[person()],vehicle:null};});h.login();await flush();assert.equal(h.state().phase,'ready');h.background();assert.equal(h.state().reveal,null);h.resume();await flush();assert.equal(count,2);h.cleanup();});
test('SQL keeps payment and confirmed-roster authority; client has no discovery or table access',()=>{const sql=fs.readFileSync('supabase/migrations/0014_secure_post_activation_reveal.sql','utf8');assert.match(sql,/mp.status = 'confirmed'/);assert.match(sql,/ap.status = 'succeeded'/);assert.match(sql,/p_viewer_member_id <> e.offering_member_id/);const s=fs.readFileSync('src/services/coordinationService.ts','utf8');assert.doesNotMatch(s,/getMasked|\.from\(|storage\.from|createSignedUrl/);});
for(const params of [{},{movementNeedId:'bad'},{movementNeedId:[need]},{movementNeedId:need,alignmentId:'secret'}])test(`route denies ${JSON.stringify(params)}`,()=>{let mounted=0;const screen=loader({react:{useState:()=>[true,()=>{}],useEffect:()=>{}},'expo-router':{Stack:{Screen:'Screen'},Redirect:'Redirect',useLocalSearchParams:()=>params},'react-native':{ScrollView:'ScrollView',Text:'Text',View:'View'},'../services/authService':{getCurrentSession:async()=>({user:{id:'test-user'}})},'../services/coordinationService':{validMovementNeed:v=>typeof v==='string'&&v===need},'../components/MovementCoordination':{MovementCoordination:()=>{mounted++;return null;}}})('src/app/movement-coordination.tsx').default;assert(text(screen()).includes('unavailable'));assert.equal(mounted,0);});
test('activation navigation seam sends only movementNeedId tocoordination',()=>{let callback,route;const screen=loader({react:{useState:()=>[true,()=>{}],useEffect:()=>{}},'expo-router':{Link:'Link',Redirect:'Redirect',Stack:{Screen:'Screen'},router:{push:r=>route=r},useLocalSearchParams:()=>({movementNeedId:need})},'react-native':{ScrollView:'ScrollView',Text:'Text',View:'View'},'../services/authService':{getCurrentSession:async()=>({user:{id:'test-user'}})},'../components/VerificationCards':{MovementFaceVerificationCard:()=>null},'../components/ActivationPaymentCard':{ActivationPaymentCard:props=>{callback=props.onContinueJourney;return null;}}})('src/app/movement-verification.tsx').default;text(screen());assert.equal(route,undefined);callback();assert.equal(route.pathname,'./movement-coordination');assert.deepEqual(Object.keys(route.params),['movementNeedId']);assert.equal(route.params.movementNeedId,need);});
