'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),crypto=require('node:crypto');
const read=p=>fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n');
const sql=read('supabase/migrations/0083_financial_movement_completion.sql');
const body=tag=>sql.match(new RegExp('AS \\$'+tag+'\\$([\\s\\S]*?)\\$'+tag+'\\$'))[1];
const need='00000000-0000-4000-8000-000000000082';
const row=(patch={})=>({journey_state:'in_progress',completion_requested_at:null,completed_at:null,can_request_completion:true,can_confirm_completion:false,response_deadline_at:null,completion_method:null,can_dispute_completion:false,dispute_active:false,settlement_state:'not_ready',...patch});
const pending=()=>row({completion_requested_at:'2026-10-03T10:00:00Z',response_deadline_at:'2026-10-03T22:00:00Z',can_request_completion:false,can_confirm_completion:true,can_dispute_completion:true,settlement_state:'awaiting_confirmation'});
const settled=()=>row({journey_state:'completed',completion_requested_at:'2026-10-03T10:00:00Z',response_deadline_at:'2026-10-03T22:00:00Z',completion_method:'requester_confirmed',completed_at:'2026-10-03T11:00:00Z',can_request_completion:false,can_confirm_completion:false,settlement_state:'settled'});
function load(p,stubs={}){const exports={};vm.runInNewContext(ts.transpileModule(read(p),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,AbortController,setTimeout,clearTimeout,require:n=>stubs[n]||{}});return exports;}
function service(data=[row()],error=null){const calls=[];return {calls,api:load('src/services/fundedCompletionService.ts',{'./coordinationService':{validMovementNeed:v=>v===need},'../lib/supabase':{supabase:{rpc:(name,args)=>{calls.push({name,args});return {abortSignal:async()=>({data,error})};}}}})};}
const signal=()=>new AbortController().signal;
test('historical 0001-0081 normalized bytes unchanged',()=>{const files=fs.readdirSync('supabase/migrations').filter(f=>/^\d{4}_/.test(f)&&Number(f.slice(0,4))<=81).sort();assert.equal(files.length,81);assert.equal(crypto.createHash('sha256').update(files.map(f=>f+'\n'+read('supabase/migrations/'+f)).join('\n')).digest('hex'),'488e25e92fe84140b1300dbc8a58a3db6e7de21256a08dc01f4c9c5c4109d223');});
test('private completion receipts exact identities immutable finite RLS no API grants',()=>{for(const n of ['funded_movement_completion_requests','funded_movement_completions']){assert(sql.includes('CREATE TABLE private.'+n));assert(sql.includes('ALTER TABLE private.'+n+' ENABLE ROW LEVEL SECURITY'));assert(sql.includes('BEFORE UPDATE OR DELETE OR TRUNCATE ON private.'+n));}assert.match(sql,/financial_agreement_id uuid NOT NULL UNIQUE REFERENCES private.funded_movement_activations/);assert.match(sql,/journey_id uuid NOT NULL UNIQUE/);assert.doesNotMatch(sql,/GRANT (?:SELECT|INSERT|UPDATE|ALL) ON (?:TABLE )?private\.funded_movement_completion/);});
test('exact asymmetric auth authority need-only input and full historical graph',()=>{for(const [tag,actor] of [['completion_request','offering_member_id'],['completion_confirm','member_needing_movement_id']]){const b=body(tag);assert(b.includes('auth.uid() IS DISTINCT FROM a.'+actor));assert(b.indexOf('funded_coordination_alignment')<b.indexOf('FOR UPDATE'));assert.match(b,/assert_funded_coordination_entry/);}assert.match(body('coordination_selector'),/movement_funding_agreement/);assert.match(body('coordination_graph'),/assert_funded_completion/);});
test('ledger amounts are stored components with contribution before offering charge',()=>{const b=body('completion_confirm');assert.match(b,/c.amount_minor/);assert.match(b,/held<r\+contribution/);assert.match(b,/withdrawable\+contribution>maximum/);assert.match(b,/revenue\+r\+o>maximum/);assert.match(b,/WHEN 'movement_contribution' THEN 2 ELSE 3/);assert.doesNotMatch(b,/calculate_financial|\/\s*2|0\.15|0\.70|quoted_platform_fee_total_minor\s*\*/);assert.match(b,/amount_minor>0/);});
test('all three posting topologies derive account identities and deterministic component keys',()=>{const b=body('completion_confirm');for(const k of ['requester_platform_charge','movement_contribution_settlement','offering_platform_charge'])assert(b.includes(k));assert.match(b,/c.kind\|\|':'\|\|c.id::text/);assert.match(b,/CASE WHEN c.component_key='offering_platform_share' THEN withdrawable_id ELSE held_id END/);assert.match(b,/CASE WHEN c.component_key='movement_contribution' THEN withdrawable_id ELSE revenue_id END/);});
test('member gates and account UPDATE locks precede provisioning and clock; no upgrade or clearing lock',()=>{const b=body('completion_confirm');assert(b.indexOf('ORDER BY m.id FOR UPDATE')<b.indexOf('ORDER BY x.id FOR UPDATE'));assert(b.indexOf('ORDER BY x.id FOR UPDATE')<b.indexOf('ensure_ngn_wallet_accounts_for_server'));assert(b.indexOf('FOR UPDATE;',b.indexOf("account_kind='platform_revenue'"))<b.indexOf('stamp:=clock_timestamp()'));assert.doesNotMatch(b,/FOR SHARE|provider_clearing/);assert.match(b,/ON CONFLICT\(account_kind,currency\) WHERE member_id IS NULL DO NOTHING/);});
test('single statement receipt ledger lifecycle dependencies then explicit full assertion',()=>{const b=body('completion_confirm');const order=['WITH evidence AS','INSERT INTO private.funded_movement_completions','FROM evidence e JOIN private.financial_components','INSERT INTO private.wallet_transactions','RETURNING id,financial_component_id,created_at','INSERT INTO private.wallet_postings','FROM transactions t JOIN components','UPDATE public.journeys','SELECT count(*) FROM postings','UPDATE public.alignments','FROM completed_journey d','PERFORM private.assert_funded_coordination_entry'];let i=b.indexOf('stamp:=clock_timestamp()');for(const value of order){const next=b.indexOf(value,i+1);assert(next>i,value);i=next;}assert.match(b,/EXCEPTION WHEN OTHERS THEN RAISE/);assert.doesNotMatch(sql,/SET CONSTRAINTS|DISABLE TRIGGER|session_replication_role/);assert.match(body('completion_request'),/WITH evidence AS[\s\S]*RETURNING journey_id,requested_at[\s\S]*UPDATE public.journeys[\s\S]*FROM evidence/);});
test('replay is before wallets and writes and returns authoritative completed projection',()=>{for(const tag of ['completion_request','completion_confirm']){const b=body(tag),start=b.indexOf('IF EXISTS'),end=b.indexOf('END IF;',start);const replay=b.slice(start,end);assert.match(replay,/RETURN QUERY SELECT \* FROM public.get_my_funded_movement_completion_status/);assert.doesNotMatch(replay,/INSERT|DELETE|UPDATE public|wallet_accounts/);}assert.doesNotMatch(body('completion_confirm'),/expires_at|has_current_alignment_face_check/);});
test('public completion writers never manipulate caller constraint modes',()=>{assert.doesNotMatch(sql,/SET CONSTRAINTS/);for(const tag of ['completion_request','completion_confirm'])assert.doesNotMatch(body(tag),/set_config|pg_trigger|tginitdeferred/);const probe=read('supabase/tests/0082_financial_movement_completion_constraint_mode_probe.cjs');for(const n of ['wallet_immediate','wallet_deferred','completion_immediate','completion_deferred','mixed','observed_mode','real_wallet_mode','confirmation rollback','completed replays'])assert(probe.includes(n),n);assert.match(probe,/CREATE CONSTRAINT TRIGGER %I AFTER INSERT ON %I.completion_mode_oracle/);});
test('fixture diagnostics preserve timestamp predicates and stress never retries failed runs',()=>{const b=read('supabase/tests/0082_financial_movement_completion_behavior.cjs')+read('docs/0082-prehardening-timestamp-diagnostics.txt');for(const s of ['0082_LOCATION_DIAGNOSTIC','producer_v_now','selected_created_at','resolved_at','expires_at','0082_CREATION_DIAGNOSTIC','creation_check_clock','expiry_check_clock','transaction_isolation','RETURN value'])assert(b.includes(s),s);assert.match(b,/NEW.created_at>private.completion_fixture_clock\(clock_timestamp\(\),'?'/);assert.match(b,/assert.equal\(count,zero\?74:75/);const c=read('supabase/tests/0082_financial_movement_completion_concurrency.cjs');assert.match(c,/if\(result.error\|\|result.status!==0\)[^]*?break;/);for(const s of ['caller_mode=','same-transaction topup','constraints.join'])assert(c.includes(s),s);});
test('historical ledger validator pins full transaction/posting proof and zero cases',()=>{const b=body('completion_graph');for(const s of ['c.amount_minor=0','n<>1','t.transaction_kind IS DISTINCT FROM kind','t.provider IS NOT NULL','t.provider_reference IS NOT NULL','t.created_at IS DISTINCT FROM receipt.completed_at','n<>2 OR matches<>2','x.amount_minor=c.amount_minor','x.direction=\'debit\'','x.direction=\'credit\'','assert_wallet_transaction_balanced','Competing settlement history forbidden'])assert(b.includes(s),s);assert.doesNotMatch(b,/x.status='active'|sum\(/);});
test('narrow lifecycle guards and prior frozen meeting/start/legacy paths preserved',()=>{for(const tag of ['journey_guard','start_alignment_guard']){assert.match(body(tag),/OLD.status='in_progress'/);assert.match(body(tag),/funded_movement_completions/);assert.doesNotMatch(body(tag),/FOR SHARE|FOR UPDATE/);}assert.doesNotMatch(sql,/FUNCTION public.(request_journey_completion|confirm_journey_completion|request_movement_end|confirm_movement_end)|FUNCTION private.protect_funded_start_meeting_point/);assert.match(body('coordination_graph'),/movement_settlements/);assert.match(body('coordination_graph'),/j.end_requested_at IS NOT NULL/);});
test('completed recovery additive real financial receipt with normal canonical context',()=>{assert.match(sql,/financial_candidates AS MATERIALIZED/);assert.match(sql,/UNION ALL/);assert.match(sql,/private.movement_coordination_context\(c.movement_need_id\)/);assert.match(sql,/ctx.journey_status='completed'/);assert.doesNotMatch(sql,/INSERT INTO private.movement_settlements|INSERT INTO public.journeys|UPDATE public.movement_offers|UPDATE public.movement_needs/);});
test('source drift clone safety and all required real race scenarios remain',()=>{const h=require('../supabase/tests/0082_financial_movement_completion_harness.cjs');assert.equal(h.expected.length,12);assert.equal(h.selectMode(0,[],false),'source');assert.throws(()=>h.selectMode(1,[],true));assert.throws(()=>h.selectMode(0,[{name:'private.assert_funded_completion'}],false));const c=read('supabase/tests/0082_financial_movement_completion_concurrency.cjs');for(const s of ['TEMPLATE template0','--format=custom','DEFAULT ACL','--use-list=','pg_blocking_pids','DROP DATABASE','fingerprint unchanged','finally','requesterTopUp','offererTopUp','provision','recovery','legacy','startReplay','queuedRace','f.superseded'])assert(c.includes(s),s);assert.doesNotMatch(c,/--no-acl|DISABLE TRIGGER|session_replication_role/);});
for(const [action,rpc,data] of [['getFundedCompletionStatus','get_my_funded_movement_completion_status',row()],['requestFundedCompletion','request_my_funded_movement_completion',pending()],['confirmFundedCompletion','confirm_my_funded_movement_completion',settled()]]){
 test(action+' exact need only safe projection',async()=>{const h=service([data]);await h.api[action](need,signal());assert.equal(h.calls[0].name,rpc);assert.deepEqual(Object.keys(h.calls[0].args),['p_movement_need_id']);assert.equal(h.calls[0].args.p_movement_need_id,need);});
 for(const bad of [null,'bad',{},[need]])test(action+' invalid selector '+JSON.stringify(bad),async()=>{const h=service();await assert.rejects(()=>h.api[action](bad,signal()));assert.equal(h.calls.length,0);});
 test(action+' abort and generic database errors',async()=>{const h=service([data]);const a=new AbortController();a.abort();await assert.rejects(()=>h.api[action](need,a.signal));assert.equal(h.calls.length,0);await assert.rejects(()=>service(null,{message:'SECRET SQL',code:'23514'}).api[action](need,signal()),/^Error: unavailable$/);});
}
for(const patch of [{journey_state:'failed'},{settlement_state:'pending'},{alignment_id:need},{completed_at:'2026-10-03T11:00:00Z'},{completion_requested_at:'2026-02-30T10:00:00Z'},{can_confirm_completion:true},{journey_state:'completed'},{settlement_state:'settled'},{completion_requested_at:'2026-10-03T10:00:00+25:00'}])test('parser fails closed '+JSON.stringify(patch),async()=>{await assert.rejects(()=>service([row(patch)]).api.getFundedCompletionStatus(need,signal()));});
test('confirmation requires authoritative settled response',async()=>{await assert.rejects(()=>service([pending()]).api.confirmFundedCompletion(need,signal()));});
test('status enums never coerce arrays or objects',async()=>{for(const patch of [{journey_state:['in_progress'],can_request_completion:false},{journey_state:{}},{settlement_state:['not_ready']},{settlement_state:{}}])await assert.rejects(()=>service([row(patch)]).api.getFundedCompletionStatus(need,signal()));});
test('historical settled request replay is parseable',async()=>{assert.equal((await service([settled()]).api.requestFundedCompletion(need,signal())).settlementState,'settled');});
test('controller synchronous duplicate guard and stale account/background response abort',async()=>{const create=load('src/state/fundedCompletionController.ts').createFundedCompletionController;let resolve,n=0,signalUsed;const wait=new Promise(r=>resolve=r);const c=create(need,{read:async()=>({canRequestCompletion:true}),request:async(_n,s)=>{signalUsed=s;n++;return wait;}});c.activate();await c.refresh();const p=c.requestCompletion();await c.requestCompletion();assert.equal(n,1);c.clear();assert(signalUsed.aborted);resolve({settlementState:'settled'});await p;assert.equal(c.getSnapshot().status,null);});
test('no capability no mutation; refresh only reads',async()=>{const create=load('src/state/fundedCompletionController.ts').createFundedCompletionController;let n=0;const c=create(need,{read:async()=>({canRequestCompletion:false,canConfirmCompletion:false}),request:async()=>{n++;},confirm:async()=>{n++;}});c.activate();await c.refresh();await c.requestCompletion();await c.confirmCompletion();assert.equal(n,0);});
test('UI exact explicit role controls waiting and settled copy',()=>{function text(e){if(e==null)return '';if(typeof e==='string')return e;if(Array.isArray(e))return e.map(text).join(' ');return text(e.props?.children);}function render(status){return text(load('src/components/FundedCompletion.tsx',{'react/jsx-runtime':{jsx:(type,props)=>({type,props}),jsxs:(type,props)=>({type,props})},'react-native':{View:'View',Text:'Text',Pressable:'Pressable'},'../hooks/useFundedCompletion':{useFundedCompletion:()=>({state:{status,busy:false,error:false}})}}).FundedCompletion({movementNeedId:need}));}assert.match(render({canRequestCompletion:true}),/Request movement completion/);assert.match(render({canConfirmCompletion:true,settlementState:'awaiting_confirmation'}),/Confirm completed/);const done=render({settlementState:'settled'});assert.match(done,/completed and settled/);assert.doesNotMatch(done,/Request movement completion|Confirm completed/);});
test('hook clears account/background/unmount and never automatically mutates',()=>{const h=read('src/hooks/useFundedCompletion.ts');for(const s of ['owner.clear()','who !== next','AppState.addEventListener','useFocusEffect','void owner.refresh()'])assert(h.includes(s));assert.doesNotMatch(h,/void .*requestCompletion|void .*confirmCompletion|void .*requestFundedCompletion|void .*confirmFundedCompletion/);assert.match(read('src/components/MeetingJourney.tsx'),/s.startAuthority === 'funded'/);});
test('funded start historical completed replay and entry remain strictly parseable',async()=>{
 const start={start_authority:'funded',meeting_point_text:'Station entrance',meeting_point_revision:1,journey_state:'completed',start_requested_at:'2026-10-03T09:00:00Z',started_at:'2026-10-03T10:00:00Z',can_edit_meeting_point:false,can_request_start:false,can_confirm_start:false};
 const api=load('src/services/meetingJourneyService.ts',{'./coordinationService':{validMovementNeed:v=>v===need},'../lib/supabase':{supabase:{rpc:()=>({abortSignal:async()=>({data:[start],error:null})})}}});
 assert.equal((await api.confirmMyFundedMovementStart(need,signal())).journeyState,'completed');
 const service=load('src/services/movementService.ts',{'../lib/supabase':{supabase:{rpc:async()=>({data:[{movement_need_id:need,journey_state:'completed',coordination_ready:true}],error:null})}}});
 const entry=await service.openMyFundedMovementCoordination(need);assert.equal(entry.journeyState,'completed');
 let navigated=0;const c=load('src/state/fundedCoordinationEntryState.ts').createFundedCoordinationEntryController(need,async()=>entry,()=>{});await c.open(()=>navigated++);assert.equal(navigated,1);
});
for(const event of ['account','background','unmount'])test('completion hook drops late mutation on '+event,async()=>{
 let auth,app,cleanup,get,resolve,actionSignal;const calls=[];const wait=new Promise(r=>resolve=r);
 const AppState={currentState:'active',addEventListener:(_e,f)=>{app=f;return {remove(){}};}};
 const create=load('src/state/fundedCompletionController.ts').createFundedCompletionController;
 const model=load('src/hooks/useFundedCompletion.ts',{react:{useMemo:f=>f(),useCallback:f=>f,useSyncExternalStore:(_s,g)=>{get=g;return g();}},'expo-router':{useFocusEffect:f=>{cleanup=f();}},'react-native':{AppState},'../lib/supabase':{supabase:{auth:{onAuthStateChange:f=>{auth=f;return {data:{subscription:{unsubscribe(){}}}};}}}},'../state/fundedCompletionController':{createFundedCompletionController:create},'../services/fundedCompletionService':{getFundedCompletionStatus:async()=>{calls.push('read');return {canRequestCompletion:true};},requestFundedCompletion:async(n,s)=>{assert.equal(n,need);actionSignal=s;calls.push('request');return wait;}}}).useFundedCompletion(need);
 assert.equal(calls.length,0);auth('SIGNED_IN',{user:{id:'offerer'}});await new Promise(r=>setImmediate(r));const p=model.requestCompletion();await model.requestCompletion();assert.deepEqual(calls,['read','request']);
 if(event==='account')auth('SIGNED_IN',{user:{id:'other'}});else if(event==='background'){AppState.currentState='background';app();}else cleanup();
 assert(actionSignal.aborted);resolve({settlementState:'settled'});await p;assert.notEqual(get().status?.settlementState,'settled');cleanup();
});

test('0082 endpoint inputs use PostgreSQL anchor and persisted parent; fresh stress modes never complete',()=>{
 const b=read('supabase/tests/0082_financial_movement_completion_behavior.cjs')+read('docs/0082-prehardening-timestamp-diagnostics.txt');
 for(const x of ['anchor:=clock_timestamp();','anchor-interval','parent_expiry:=anchor+interval','SELECT created_at INTO STRICT anchor','p_latitude,p_longitude,anchor,parent_expiry','source_row','owner_endpoints','synthetic_offsets','0082_PROPOSAL_DIAGNOSTIC','requester_check_clock','materialization_check_clock'])assert(b.includes(x),x);
 const stress=read('supabase/tests/0082_financial_movement_completion_settlement_stress.cjs');
 for(const mode of ['--fixture-only','--provider-only'])assert(stress.includes(mode));
 assert.equal((stress.match(/run<=200/g)||[]).length,2);
 for(const x of ['assert_movement_location_resolution_evidence','assert_trusted_location_state_evidence','resolved_count<>4','target.expires_at IS NULL','no retries'])assert(stress.includes(x),x);
 assert(stress.includes('Fixture-only path called completion'));assert(stress.includes('Provider-only path called completion'));
});

test('proposal-layer audit captures exact short-circuit comparisons and stops before completion',()=>{
 const b=read('supabase/tests/0082_financial_movement_completion_behavior.cjs')+read('docs/0082-prehardening-timestamp-diagnostics.txt');
 for(const x of ['failed_predicates','deltas_microseconds','completion_fixture_proposal_sources(NEW)','provider_resolution','provider_state','diagnostic_snapshot','0082_DISCOVERY_DIAGNOSTIC','before_parent','future_delta_microseconds'])assert(b.includes(x),x);
 for(const x of ['offering_accepted_at','requester_accepted_at','materialized_at'])assert(b.includes('NEW.'+x+'>private.completion_fixture_clock(clock_timestamp()'));
 const s=read('supabase/tests/0082_financial_movement_completion_settlement_stress.cjs');
 const branch=s.slice(s.indexOf("if(process.argv.includes('--proposal-only'))"),s.indexOf("if(process.argv.includes('--provider-only'))"));
 assert(branch.includes('run<=500'));assert(branch.includes('INSERT INTO pg_temp.funding_fixture VALUES'));assert(branch.includes('assert_financial_proposal_materialization(p)'));assert(branch.includes('exactly three components'));
 assert.doesNotMatch(branch,/migrationBody|prepare_completion|completion_result\(/);assert(branch.includes('finally'));assert(branch.includes('snapshot),before'));assert.doesNotMatch(branch,/Date\.|new Date|retry\(/);
});

test('discovery audit is isolated, deterministic and preserves the complete first-failure artifact',()=>{
 const b=read('supabase/tests/0082_financial_movement_completion_behavior.cjs')+read('docs/0082-prehardening-timestamp-diagnostics.txt');
 for(const s of ['completion_fixture_discovery_matrix','predicate_matrix','right_expected','label_length','timestamp_provenance'])assert(b.includes(s),s);
 const c=read('supabase/tests/0082_financial_movement_completion_settlement_stress.cjs');
 const branch=c.slice(c.indexOf("if(process.argv.includes('--discovery-only'))"),c.indexOf("if(process.argv.includes('--proposal-diagnostics'))"));
 for(const s of ['run<=1000','gen_random_uuid()','INTO STRICT evidence','e.resolved_location_reference_id=location','assert_trusted_location_discovery_area','assert_movement_location_resolution_evidence','assert_trusted_location_state_evidence','artifact.diagnostic','0082-discovery-area-stress-result.json','failure=e;break','snapshot),before'])assert(branch.includes(s),s);
 assert.doesNotMatch(branch,/migrationBody|prepare_completion|completion_result\(|requester_accept\(|Date\.|new Date|pg_sleep/);
});
