'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),crypto=require('node:crypto');
const read=p=>fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n');const source=read('supabase/migrations/0081_financial_movement_start.sql');
const body=tag=>source.match(new RegExp('AS \\$'+tag+'\\$([\\s\\S]*?)\\$'+tag+'\\$'))[1];
const need='00000000-0000-4000-8000-000000000081';
const row=(x={})=>({meeting_point_text:'Station entrance',meeting_point_revision:1,journey_state:'not_started',start_requested_at:'2026-10-03T10:00:00Z',started_at:null,can_edit_meeting_point:false,can_request_start:false,can_confirm_start:false,start_authority:'funded',...x});
function load(p,stubs={}){const exports={};vm.runInNewContext(ts.transpileModule(read(p),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,AbortController,setTimeout,clearTimeout,require:n=>stubs[n]||{}});return exports;}
function service(data=[row()],error=null){const calls=[];const api=load('src/services/meetingJourneyService.ts',{'./coordinationService':{validMovementNeed:v=>typeof v==='string'&&v===need},'../lib/supabase':{supabase:{rpc:(name,args)=>{calls.push({name,args});return {abortSignal:async()=>({data,error})};}}}});return {api,calls};}
const signal=()=>new AbortController().signal;
test('historical 0001-0080 normalized bytes unchanged',()=>{const files=fs.readdirSync('supabase/migrations').filter(f=>/^00(?:[0-7]\d|80)_/.test(f)).sort();assert.equal(files.length,80);assert.equal(crypto.createHash('sha256').update(files.map(f=>f+'\n'+read('supabase/migrations/'+f)).join('\n')).digest('hex'),'3cb6899275f2f9c99290c6f288ca41c4f5e0c2761580fe7e4bdcba845e0c3a7e');});
test('exact private append-only RLS provenance, no duplicated economics or principals',()=>{for(const name of ['funded_movement_start_requests','funded_movement_starts']){assert(source.includes('CREATE TABLE private.'+name));assert(source.includes('ALTER TABLE private.'+name+' ENABLE ROW LEVEL SECURITY'));assert(source.includes('BEFORE UPDATE OR DELETE OR TRUNCATE ON private.'+name));}assert.match(source,/journey_id uuid NOT NULL UNIQUE/);assert.match(source,/meeting_point_revision bigint NOT NULL/);assert.doesNotMatch(source,/CREATE TABLE[^]*?member_id uuid/);});
test('exact asymmetric auth.uid authority and canonical locks',()=>{for(const [tag,actor] of [['start_request','offering_member_id'],['start_confirm','member_needing_movement_id']]){const b=body(tag);assert(b.includes('auth.uid() IS DISTINCT FROM a.'+actor));assert(b.indexOf('funded_coordination_alignment')<b.indexOf('FOR UPDATE'));assert(b.indexOf('FOR UPDATE')<b.indexOf('FOR SHARE'));assert(b.indexOf('FOR SHARE')<b.indexOf('clock_timestamp()'));}const selector=body('coordination_selector');assert(selector.indexOf('FOR SHARE')<selector.indexOf('FOR UPDATE'));for(const name of ['movement_funding_agreement','assert_funded_activation'])assert(selector.includes(name));});
test('only exact new construction constraints deferred then drained within rollback subtransaction',()=>{for(const tag of ['start_request','start_confirm']){const b=body(tag);assert.match(b,/BEGIN\s+SET CONSTRAINTS private.funded_start_request_complete,private.funded_start_complete,public.funded_start_journey_complete,public.funded_start_alignment_complete DEFERRED/);assert.match(b,/SET CONSTRAINTS [^;]+ IMMEDIATE/);assert.match(b,/EXCEPTION WHEN OTHERS THEN RAISE/);assert.doesNotMatch(b,/SET CONSTRAINTS ALL|now\(/i);}});
test('receipt-first atomic transition preserves request activation vehicle and identity',()=>{const b=body('start_confirm');assert(b.indexOf('INSERT INTO private.funded_movement_starts')<b.indexOf('UPDATE public.journeys'));assert.match(b,/status='in_progress',started_at=stamp/);assert.match(b,/UPDATE public.alignments x SET status='in_progress'/);assert.doesNotMatch(b,/SET[^;]*(activated_at|vehicle_id|start_requested_at)=/);assert.match(body('start_request'),/INSERT INTO private.funded_movement_start_requests VALUES\(a.id,j.id,stamp,mp.revision\)/);});
test('exact historical replay branches contain no writes or current expiry/face gates',()=>{for(const tag of ['start_request','start_confirm']){const b=body(tag);const replay=b.slice(b.indexOf('IF EXISTS'),b.indexOf('END IF;',b.indexOf('IF EXISTS')));assert.doesNotMatch(replay,/INSERT|UPDATE public|DELETE/);assert.match(replay,/RETURN QUERY SELECT \* FROM public.get_my_movement_start_status/);assert.doesNotMatch(b,/has_current_alignment_face_check|expires_at|g.status='current'/);}});
test('graph validates exact receipt/journey times, frozen revision, no end/completion and funded history',()=>{const b=body('coordination_graph');for(const text of ['request.journey_id IS DISTINCT FROM j.id','request.requested_at IS DISTINCT FROM j.start_requested_at','mp.revision IS DISTINCT FROM request.meeting_point_revision','started.started_at IS DISTINCT FROM j.started_at',"a.status<>'in_progress'",'j.completion_requested_at IS NOT NULL','j.end_requested_at IS NOT NULL','private.assert_funded_activation'])assert(b.includes(text),text);});
test('guards narrowly allow receipt-backed transitions and reject terminal/rebinding writes',()=>{for(const tag of ['journey_guard','start_alignment_guard']){assert.match(body(tag),/RAISE EXCEPTION/);assert.match(body(tag),/funded_movement_starts/);assert.doesNotMatch(body(tag),/FOR UPDATE|FOR SHARE/);}assert.match(body('journey_guard'),/OLD.status='not_started'/);assert.match(body('start_meeting_guard'),/Financial start meeting point is frozen/);assert.match(source,/CREATE CONSTRAINT TRIGGER funded_start_complete/);});
test('legacy start/end/settlement, recovery and reveal protections retained without replacements',()=>{assert.doesNotMatch(source,/FUNCTION public.(request_journey_start|confirm_journey_start|request_my_movement_start|confirm_my_movement_start|request_movement_end|list_my_active_movement_continuations)|FUNCTION private.post_activation_reveal_subjects/);const old=read('supabase/migrations/0080_funded_movement_coordination_entry.sql');assert.match(old,/Financial legacy settlement unavailable/);assert.match(old,/Financial coordination lifecycle unavailable/);assert.match(read('supabase/migrations/0056_active_movement_coordination_recovery.sql'),/a.status = 'in_progress'/);});
test('no forbidden writers or bypass flags',()=>{assert.doesNotMatch(source,/(INSERT INTO|UPDATE|DELETE FROM) (private\.(wallet_|financial_agreements|financial_components|movement_funding_holds|movement_settlements|funded_movement_activations)|public\.(movement_offers|movement_needs|movement_participants))/);assert.doesNotMatch(source,/set_config|session_replication_role|DISABLE TRIGGER|advisory_lock|latitude|longitude/);});
for(const action of ['requestMyFundedMovementStart','confirmMyFundedMovementStart']){
 test(action+' sends need only and exact authenticated response',async()=>{const h=service([row(action.startsWith('confirm')?{journey_state:'in_progress',started_at:'2026-10-03T11:00:00Z'}:{})]);const result=await h.api[action](need,signal());assert.equal(result.startAuthority,'funded');assert.deepEqual(Object.keys(h.calls[0].args),['p_movement_need_id']);assert.equal(h.calls[0].args.p_movement_need_id,need);assert.equal(h.calls[0].name,action.startsWith('request')?'request_my_funded_movement_start':'confirm_my_funded_movement_start');});
 for(const value of [null,'bad',[need],{}])test(action+' rejects selector '+JSON.stringify(value),async()=>{const h=service();await assert.rejects(()=>h.api[action](value,signal()),/unavailable/);assert.equal(h.calls.length,0);});
 for(const data of [null,[],[row(),row()],[null],[row({journey_id:need})],[row({start_authority:'legacy'})],[row({start_authority:'other'})],[row({journey_state:'cancelled'})],[row({journey_state:'completed',started_at:'2026-10-03T11:00:00Z'})],[row({journey_state:'in_progress',started_at:null})],[row({journey_state:'in_progress',started_at:'2026-10-03T09:00:00Z'})]])test(action+' fail-closed shape '+JSON.stringify(data),async()=>{await assert.rejects(()=>service(data).api[action](need,signal()),/unavailable/);});
 test(action+' raw SQL hidden and aborted call avoids transport',async()=>{await assert.rejects(()=>service(null,{code:'23514',message:'SECRET'}).api[action](need,signal()),/^Error: unavailable$/);const h=service();const a=new AbortController();a.abort();await assert.rejects(()=>h.api[action](need,a.signal));assert.equal(h.calls.length,0);});
}
test('controller uses only backend authority and synchronous duplicate guard',async()=>{const {createMeetingController:create}=load('src/state/meetingJourneyController.ts');let resolve,count=0,authority,observedSignal;const wait=new Promise(r=>resolve=r);const initial={startAuthority:'funded',canRequestStart:true,meetingPointRevision:1};const c=create(need,{read:async()=>initial,request:async(n,s,a)=>{assert.equal(n,need);observedSignal=s;authority=a;count++;return wait;}});c.activate();await c.refresh();const p=c.requestStart();await c.requestStart();assert.equal(count,1);assert.equal(authority,'funded');c.clear();assert(observedSignal.aborted);resolve(initial);await p;assert.equal(c.getSnapshot().status,null);});
test('hook routes explicit financial actions only; lifecycle abort retained',()=>{const h=read('src/hooks/useMeetingJourney.ts');assert.match(h,/authority === 'funded' \? requestMyFundedMovementStart/);assert.match(h,/authority === 'funded' \? confirmMyFundedMovementStart/);for(const text of ['owner.clear()','who !== next','AppState.addEventListener','useFocusEffect'])assert(h.includes(text));assert.doesNotMatch(h,/void .*requestMyFundedMovementStart|void .*confirmMyFundedMovementStart/);});
test('current source and installed drift modes fail closed; clone/fingerprint/cleanup retained',()=>{const h=require('../supabase/tests/0081_financial_movement_start_harness.cjs');assert.equal(h.expected.length,11);assert.equal(h.selectMode(0,[],false),'source');assert.throws(()=>h.selectMode(1,[],true),/mismatch/);for(const kind of ['behavior','concurrency'])new vm.Script(read('supabase/tests/0081_financial_movement_start_'+kind+'.cjs'));const c=read('supabase/tests/0081_financial_movement_start_concurrency.cjs');for(const text of ['TEMPLATE template0','--format=custom','DEFAULT ACL','--use-list=','pg_blocking_pids','DROP DATABASE','verify(query, database)','fingerprint unchanged','finally'])assert(c.includes(text),text);assert.doesNotMatch(c,/--no-acl|DISABLE TRIGGER|session_replication_role/);});
test('entry historical in-progress replay remains strictly parseable',async()=>{const api=load('src/services/movementService.ts',{'../lib/supabase':{supabase:{rpc:async()=>({data:[{movement_need_id:need,journey_state:'in_progress',coordination_ready:true}],error:null})}}});assert.equal((await api.openMyFundedMovementCoordination(need)).journeyState,'in_progress');});

for(const action of ['requestMyFundedMovementStart','confirmMyFundedMovementStart'])test(action+' requires persisted handshake evidence and calendar-valid time',async()=>{
 for(const patch of [{start_requested_at:null},{start_requested_at:'2026-02-30T10:00:00Z'},{start_requested_at:'2026-10-03T10:00:00+25:00'}])await assert.rejects(()=>service([row(patch)]).api[action](need,signal()),/unavailable/);
});
test('confirmation response must actually be in progress',async()=>{await assert.rejects(()=>service([row()]).api.confirmMyFundedMovementStart(need,signal()),/unavailable/);});
test('request historical replay accepts exactly persisted in-progress status',async()=>{const r=await service([row({journey_state:'in_progress',started_at:'2026-10-03T11:00:00Z'})]).api.requestMyFundedMovementStart(need,signal());assert.equal(r.journeyState,'in_progress');});
test('read projection accepts funded phases and legacy authority without inference',async()=>{for(const [patch,authority] of [[{start_requested_at:null,can_edit_meeting_point:true,can_request_start:true},'funded'],[{can_confirm_start:true},'funded'],[{journey_state:'in_progress',started_at:'2026-10-03T11:00:00Z'},'funded'],[{start_authority:'legacy'},'legacy']]){const h=service([row(patch)]);assert.equal((await h.api.getMeetingJourneyStatus(need,signal())).startAuthority,authority);assert.equal(h.calls[0].name,'get_my_movement_start_status');}});
test('financial hook actions select exact RPC seam and abort/drop late success on account change',async()=>{
 let auth,cleanup,get,resolve,requestSignal;const calls=[];const wait=new Promise(r=>resolve=r);
 const {createMeetingController:create}=load('src/state/meetingJourneyController.ts');
 const initial={startAuthority:'funded',meetingPointRevision:1,canRequestStart:true,canConfirmStart:false};
 const model=load('src/hooks/useMeetingJourney.ts',{
  react:{useMemo:f=>f(),useCallback:f=>f,useSyncExternalStore:(_s,g)=>{get=g;return g();}},'expo-router':{useFocusEffect:f=>{cleanup=f();}},
  'react-native':{AppState:{currentState:'active',addEventListener:()=>({remove(){}})}},
  '../lib/supabase':{supabase:{auth:{onAuthStateChange:f=>{auth=f;return {data:{subscription:{unsubscribe(){}}}};}}}},
  '../state/meetingJourneyController':{createMeetingController:create},
  '../services/meetingJourneyService':{getMeetingJourneyStatus:async()=>{calls.push('read');return initial;},requestMyFundedMovementStart:async(n,s)=>{assert.equal(n,need);requestSignal=s;calls.push('funded-request');return wait;},requestMovementStart:async()=>{throw Error('Legacy path must not run');},confirmMovementStart:async()=>{throw Error('Legacy path must not run');}}
 }).useMeetingJourney(need);
 assert.equal(calls.length,0);auth('SIGNED_IN',{user:{id:'offerer'}});await new Promise(r=>setImmediate(r));assert.deepEqual(calls,['read']);
 const pending=model.requestStart();await model.requestStart();assert.deepEqual(calls,['read','funded-request']);auth('SIGNED_IN',{user:{id:'other'}});assert(requestSignal.aborted);
 resolve({...initial,startRequestedAt:'2026-10-03T10:00:00Z'});await pending;assert.notEqual(get().status?.startRequestedAt,'2026-10-03T10:00:00Z');cleanup();
});
