'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),cp=require('node:child_process');
const need='00000000-0000-4000-8000-000000000086',instant='2026-10-05T12:00:00.123+00:00';
const plain=x=>JSON.parse(JSON.stringify(x)),signal=()=>new AbortController().signal;
function load(file,stubs={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,AbortController,setTimeout,clearTimeout,...globals,require:n=>n==='react/jsx-runtime'?require(n):stubs[n]||{}});return exports;}
const row=(patch={})=>({dispute_active:false,can_open:true,opened_by_me:false,opened_at:null,...patch});
const active=row({dispute_active:true,can_open:false,opened_by_me:true,opened_at:instant});
function service(data=[row()],error=null,after){const calls=[];const api=load('src/services/movementDisputeService.ts',{'../lib/supabase':{supabase:{rpc:(...args)=>{calls.push(plain(args));return {abortSignal:async()=>{after?.();return {data,error};}};}}}});return {api,calls};}
test('0086 exact RPC args have only need and category',async()=>{const h=service();await h.api.getMovementDisputeStatus(need,signal());for(const reason of ['unable_to_agree','movement_concern'])await h.api.openMovementDispute(need,signal(),reason);assert.deepEqual(h.calls,[['get_my_funded_movement_dispute_status',{p_movement_need_id:need}],...['unable_to_agree','movement_concern'].map(p_reason_category=>['open_my_funded_movement_dispute',{p_movement_need_id:need,p_reason_category}])]);});
test('0086 parser accepts eligible, ineligible and both active principal projections',async()=>{for(const r of [row(),row({can_open:false}),active,{...active,opened_by_me:false}])assert.deepEqual(plain(await service([r]).api.getMovementDisputeStatus(need,signal())),{active:r.dispute_active,canOpen:r.can_open,openedByMe:r.opened_by_me,openedAt:r.opened_at});});
for(const [label,patch] of Object.entries({private_member:{member_id:need},private_graph:{alignment_id:need},private_journey:{journey_id:need},private_agreement:{financial_agreement_id:need},private_component:{financial_component_id:need},private_wallet:{wallet_id:need},provider:{provider:'secret'},raw_reason:{reason_category:'movement_concern'},active_type:{dispute_active:1},can_type:{can_open:'true'},owner_type:{opened_by_me:null},inactive_owner:{opened_by_me:true},inactive_time:{opened_at:instant}}))test('0086 reject malformed '+label,async()=>{await assert.rejects(service([row(patch)]).api.getMovementDisputeStatus(need,signal()),{message:'movement_review_unavailable'});});
for(const time of [null,'infinity','2026-02-30T12:00:00Z','2026-10-05','2026-10-05T24:00:00Z','2026-10-05T12:60:00Z','2026-10-05T12:00:00+00:60'])test('0086 reject invalid active instant '+time,async()=>{await assert.rejects(service([{...active,opened_at:time}]).api.getMovementDisputeStatus(need,signal()));});
test('0086 rejects contradictory active eligibility and incomplete row shapes',async()=>{for(const data of [null,{},[],[null],[active,active],[{...active,can_open:true}]])await assert.rejects(service(data).api.getMovementDisputeStatus(need,signal()));for(const key of Object.keys(row())){const r=row();delete r[key];await assert.rejects(service([r]).api.getMovementDisputeStatus(need,signal()));}});
test('0086 invalid selector/category avoids transport',async()=>{for(const bad of [null,1,{},'', 'bad']){const h=service();await assert.rejects(h.api.getMovementDisputeStatus(bad,signal()));assert.equal(h.calls.length,0);}for(const reason of ['',undefined,null,1,'movement_concern ','refund']){const h=service();await assert.rejects(h.api.openMovementDispute(need,signal(),reason));assert.equal(h.calls.length,0);}});
test('0086 pre/post abort and backend error hide secrets',async()=>{const a=new AbortController();a.abort();const h=service();await assert.rejects(h.api.getMovementDisputeStatus(need,a.signal));assert.equal(h.calls.length,0);const b=new AbortController();await assert.rejects(service([active],null,()=>b.abort()).api.openMovementDispute(need,b.signal,'movement_concern'));await assert.rejects(service(null,{message:'SQL wallet secret'}).api.getMovementDisputeStatus(need,signal()),{message:'movement_review_unavailable'});});
const create=load('src/state/movementDisputeController.ts').createMovementDisputeController;
const available={active:false,canOpen:true,openedByMe:false,openedAt:null},review={active:true,canOpen:false,openedByMe:true,openedAt:instant};
const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
test('0086 initial load only reads; explicit write waits fresh read and guards taps',async()=>{const wait=deferred();let reads=0,writes=0;const c=create(need,{read:async()=>++reads===1?available:wait.promise,open:async()=>{writes++;return review;}});await c.openDispute('movement_concern');assert.equal(writes,0);c.activate();await c.refresh();assert.equal(reads,1);const pending=c.openDispute('movement_concern');await c.openDispute('movement_concern');await c.refresh();await new Promise(setImmediate);assert.equal(writes,1);assert.equal(c.getSnapshot().status,available);wait.resolve(review);await pending;assert.equal(c.getSnapshot().status,review);await c.openDispute('movement_concern');assert.equal(writes,1);});
for(const stage of ['read','mutation','refresh'])test('0086 clear drops stale '+stage+' response',async()=>{const wait=deferred();let reads=0,writes=0;const c=create(need,{read:async()=>{reads++;return stage==='read'||(stage==='refresh'&&reads>1)?wait.promise:available;},open:async()=>{writes++;return stage==='mutation'?wait.promise:review;}});c.activate();let pending=c.refresh();if(stage!=='read'){await pending;pending=c.openDispute('unable_to_agree');await new Promise(setImmediate);}c.clear();wait.resolve(review);await pending;assert.equal(c.getSnapshot().status,null);await c.openDispute('movement_concern');assert.equal(writes,stage==='read'?0:1);});
test('0086 failed read after successful mutation clears controls',async()=>{let reads=0;const c=create(need,{read:async()=>{if(++reads>1)throw Error('private');return available;},open:async()=>review});c.activate();await c.refresh();await c.openDispute('movement_concern');assert.deepEqual(plain(c.getSnapshot()),{status:null,busy:false,error:true});});
test('0086 timeout aborts request and drops late success',async()=>{let timeout;const wait=deferred();const C=load('src/state/movementDisputeController.ts',{}, {setTimeout:fn=>{timeout=fn;return 1;},clearTimeout:()=>{}}).createMovementDisputeController;let sig;const c=C(need,{read:async(_n,s)=>{sig=s;return wait.promise;},open:async()=>review});c.activate();const pending=c.refresh();timeout();assert.equal(sig.aborted,true);wait.resolve(review);await pending;assert.deepEqual(plain(c.getSnapshot()),{status:null,busy:false,error:true});});
function hookHarness(){let auth,app,cleanup,snapshot;const calls=[];const AppState={currentState:'active',addEventListener:(_e,fn)=>{app=fn;return {remove:()=>calls.push('remove')};}};const api=load('src/hooks/useMovementDispute.ts',{react:{useMemo:fn=>fn(),useCallback:fn=>fn,useSyncExternalStore:(_s,get)=>{snapshot=get;return get();}},'react-native':{AppState},'expo-router':{useFocusEffect:fn=>cleanup=fn()},'../lib/supabase':{supabase:{auth:{onAuthStateChange:fn=>{auth=fn;return {data:{subscription:{unsubscribe:()=>calls.push('unsubscribe')}}};}}}},'../state/movementDisputeController':{createMovementDisputeController:create},'../services/movementDisputeService':{getMovementDisputeStatus:async()=>{calls.push('read');return available;},openMovementDispute:async()=>{calls.push('open');return review;}}});const model=api.useMovementDispute(need);return {model,calls,state:()=>snapshot(),login:id=>auth('SIGNED_IN',id?{user:{id}}:null),background:()=>{AppState.currentState='background';app();},resume:()=>{AppState.currentState='active';app();},cleanup:()=>cleanup()};}
test('0086 focus account background resume unmount never open automatically',async()=>{const h=hookHarness();assert.deepEqual(h.calls,[]);h.login('requester');await new Promise(setImmediate);assert.equal(h.state().status.canOpen,true);h.background();assert.equal(h.state().status,null);await h.model.openDispute('movement_concern');h.resume();await new Promise(setImmediate);h.login('offerer');assert.equal(h.state().status,null);await new Promise(setImmediate);h.cleanup();h.resume();h.login('requester');await new Promise(setImmediate);await h.model.openDispute('movement_concern');assert.equal(h.state().status,null);assert.deepEqual(h.calls,['read','read','read','remove','unsubscribe']);});
function ui(status,busy=false){const calls=[],model={state:{status,busy,error:false},refresh:()=>calls.push('read'),openDispute:r=>calls.push(r)};const C=load('src/components/MovementDispute.tsx',{'react-native':{View:'View',Text:'Text',Pressable:'Pressable'},'../hooks/useMovementDispute':{useMovementDispute:n=>{assert.equal(n,need);return model;}}}).MovementDispute;let text='';const buttons=[];function visit(v){if(v==null)return;if(typeof v==='string'){text+=v+' ';return;}if(Array.isArray(v)){v.forEach(visit);return;}if(v.type==='Pressable')buttons.push(v);visit(v.props?.children);}visit(C({movementNeedId:need}));return {calls,text,buttons};}
test('0086 human action requires press and stays separate from Not yet',()=>{const h=ui(available);assert.deepEqual(h.calls,[]);assert.match(h.text,/Report a problem with this movement/);assert.doesNotMatch(h.text,/Not yet/);h.buttons[0].props.onPress();h.buttons[1].props.onPress();assert.deepEqual(h.calls,['unable_to_agree','movement_concern']);for(const b of ui(available,true).buttons)assert.equal(b.props.disabled,true);});
test('0086 review copy neutral and no reopening controls',()=>{for(const owner of [true,false]){const h=ui({...review,openedByMe:owner});assert.match(h.text,/This movement is under review. The held movement amount remains on hold./);assert.doesNotMatch(h.text,/refund|winner|unable_to_agree|movement_concern|alignment|wallet/);assert.equal(h.buttons.length,1);assert.deepEqual(h.calls,[]);}assert.equal(ui(null).buttons.length,0);assert.equal(ui({...available,canOpen:false}).buttons.length,1);});
test('0086 append-only additive migration has no money writes or historical rewrites',()=>{const sql=fs.readFileSync('supabase/migrations/0086_funded_unilateral_dispute_freeze.sql','utf8');assert.doesNotMatch(sql,/CREATE OR REPLACE|INSERT INTO (?:public.journeys|private.wallet_)|UPDATE (?:public|private)\.|FOR UPDATE[^]*wallet_accounts|DISABLE TRIGGER|session_replication_role/);assert.match(sql,/ORDER BY m.id FOR UPDATE/);assert.match(sql,/clock_timestamp\(\)/);assert.match(sql,/BEFORE UPDATE OR DELETE OR TRUNCATE/);assert.match(sql,/dispute_blocks_financial_disposition/);});
test('0086 all historical migration normalized bytes remain exact',()=>{const prefix=cp.execFileSync('git',['rev-parse','--show-prefix'],{encoding:'utf8'}).trim();const files=fs.readdirSync('supabase/migrations').filter(n=>/^\d{4}_/.test(n)&&n.slice(0,4)<='0085');assert.equal(files.length,85);for(const name of files)assert.equal(fs.readFileSync('supabase/migrations/'+name,'utf8').replace(/\r\n/g,'\n'),cp.execFileSync('git',['show','HEAD:'+prefix+'supabase/migrations/'+name],{encoding:'utf8'}).replace(/\r\n/g,'\n'),name);});
test('0086 metadata validators never sample a clock or compare opening to another timestamp',()=>{
 const sql=fs.readFileSync('supabase/migrations/0086_funded_unilateral_dispute_freeze.sql','utf8');
 for(const name of ['assert_funded_dispute','require_funded_dispute_actor']){
  const body=sql.slice(sql.indexOf('CREATE FUNCTION private.'+name),sql.indexOf('$$;',sql.indexOf('CREATE FUNCTION private.'+name)));
  assert.doesNotMatch(body,/clock_timestamp|opened_at\s*[<>]|[<>]\s*(?:d|NEW)\.opened_at/);
  assert.match(body,/NOT isfinite\((?:d|NEW)\.opened_at\)/);
  assert.match(body,/financial_agreement_id IS DISTINCT FROM e.financial_agreement_id/);
 }
 assert.equal((sql.match(/clock_timestamp\(\)/g)||[]).length,1);
 assert.match(sql,/auth.uid\(\),clock_timestamp\(\),p_reason_category/);
 const graph=sql.slice(sql.indexOf('CREATE FUNCTION private.assert_undisposed_funded_graph'),sql.indexOf('$no_travel_graph$;'));
 assert.doesNotMatch(graph,/clock_timestamp|created_at\s*[<>]|requested_at\s*[<>]|declined_at\s*[<>]|released_at\s*[<>]/);
 assert.match(graph,/Undisposed pre-start graph required/);
 assert.match(graph,/assert_funded_completion\(a.id\)/);
});
test('0086 client does not impose future/past ordering on server opening metadata',async()=>{
 for(const opened_at of ['2000-01-01T00:00:00Z','2099-01-01T00:00:00Z'])assert.equal((await service([{...active,opened_at}]).api.getMovementDisputeStatus(need,signal())).openedAt,opened_at);
});
test('0086 client cannot serialize caller-provided opening metadata',async()=>{
 const h=service();await h.api.openMovementDispute(need,signal(),'movement_concern',{opened_at:instant});assert.deepEqual(h.calls,[['open_my_funded_movement_dispute',{p_movement_need_id:need,p_reason_category:'movement_concern'}]]);
 const bad=service();await assert.rejects(bad.api.openMovementDispute(need,signal(),{reason_category:'movement_concern',opened_at:instant}));assert.equal(bad.calls.length,0);
});
