'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
const need='00000000-0000-4000-8000-000000000088';
const row=patch=>({journey_state:'not_started',end_status:'no_travel_held',requested_by_me:false,action_required_from_me:false,requested_at:'2026-10-06T12:00:00Z',completed_at:null,funding_disposition:'held_review_required',released_minor:null,currency:'NGN',...patch});
function load(file,stubs){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,AbortController,require:n=>stubs[n]||{}});return exports;}
function service(value){const calls=[];return {calls,api:load('src/services/movementEndService.ts',{'../lib/supabase':{supabase:{rpc:(name,args)=>{calls.push({name,args});return {abortSignal:async()=>({data:[value],error:null})};}}}})};}
test('0088 held no-travel projection preserves exact public RPC inputs and never claims refund',async()=>{const h=service(row());for(const name of ['getMovementEndStatus','requestMovementEnd','confirmMovementEnd']){const s=await h.api[name](need,new AbortController().signal);assert.equal(s.fundingDisposition,'held_review_required');assert.equal(s.releasedMinor,null);assert.equal(s.endStatus,'no_travel_held');assert.equal(s.actionRequiredFromMe,false);}for(const call of h.calls)assert.deepEqual(JSON.parse(JSON.stringify(call.args)),{p_movement_need_id:need});});
for(const patch of [{released_minor:0},{released_minor:123},{funding_disposition:'released_to_me'},{funding_disposition:'released_to_requester'},{funding_disposition:'held'},{funding_disposition:'legacy'},{journey_state:'cancelled'},{journey_state:'completed'},{end_status:'mutual_no_travel'},{requested_by_me:true},{action_required_from_me:true},{requested_at:null},{completed_at:'2026-10-06T12:00:00Z'},{currency:'USD'},{financial_agreement_id:need}])test('0088 rejects contradictory/private held projection '+JSON.stringify(patch),async()=>{await assert.rejects(service(row(patch)).api.getMovementEndStatus(need,new AbortController().signal),{message:'movement_end_unavailable'});});
test('0088 held UI has truthful money copy and only refresh after recorded non-travel',()=>{const jsx=(type,props)=>({type,props});const {MovementEnd}=load('src/components/MovementEnd.tsx',{'react/jsx-runtime':{jsx,jsxs:jsx},'react-native':{View:'View',Text:'Text',Pressable:'Pressable'},'../hooks/useMovementEnd':{useMovementEnd:()=>({state:{status:{journeyState:'not_started',endStatus:'no_travel_held',fundingDisposition:'held_review_required'},busy:false,error:null},refresh(){}})}});const nodes=[];function walk(n){if(Array.isArray(n))n.forEach(walk);else if(n&&typeof n==='object'){nodes.push(n);walk(n.props?.children);}}walk(MovementEnd({movementNeedId:need}));const text=nodes.filter(n=>n.type==='Text').map(n=>n.props.children).join(' ');assert.match(text,/contribution remains held/);assert.match(text,/No money was returned/);assert.match(text,/platform fee remains non-refundable/);assert.equal(nodes.filter(n=>n.type==='Pressable').length,1);assert.doesNotMatch(text,/returned to your Movement Balance|Confirm movement ended/);});
test('0088 held history has finite provenance and no future clock validation',()=>{const sql=fs.readFileSync('supabase/migrations/0088_funded_activation_fee_finalization.sql','utf8');const body=sql.slice(sql.indexOf('CREATE FUNCTION private.assert_held_no_travel'),sql.indexOf('CREATE FUNCTION private.require_held_no_travel_actor'));assert.doesNotMatch(body,/clock_timestamp|observed_at[<>]|requested_at[<>]/);assert.match(body,/pending_start_requested_at IS DISTINCT FROM j.start_requested_at/);assert.match(body,/PERFORM private.assert_funded_no_travel/);});
