'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),crypto=require('node:crypto'),cp=require('node:child_process');
const read=p=>fs.readFileSync(p,'utf8').replace(/\r\n/g,'\n'),sql=read('supabase/migrations/0087_funded_completion_timeout_recovery.sql'),need='00000000-0000-4000-8000-000000000087';
function load(file,stubs={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(read(file),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,AbortController,setTimeout,clearTimeout,require:n=>stubs[n]||{},...globals});return exports;}
const row=(patch={})=>({journey_state:'in_progress',completion_requested_at:null,completed_at:null,can_request_completion:true,can_confirm_completion:false,response_deadline_at:null,completion_method:null,can_dispute_completion:false,dispute_active:false,settlement_state:'not_ready',...patch});
const pending=patch=>row({completion_requested_at:'2026-10-03T10:00:00Z',response_deadline_at:'2026-10-03T22:00:00Z',can_request_completion:false,can_confirm_completion:true,can_dispute_completion:true,settlement_state:'awaiting_confirmation',...patch});
const review=()=>pending({dispute_active:true,can_confirm_completion:false,can_dispute_completion:false,settlement_state:'under_review'});
const completed=method=>pending({journey_state:'completed',completed_at:'2000-01-01T00:00:00Z',completion_method:method,can_confirm_completion:false,can_dispute_completion:false,settlement_state:'settled'});
function service(data=[pending()],error=null){const calls=[];return {calls,api:load('src/services/fundedCompletionService.ts',{'./coordinationService':{validMovementNeed:n=>n===need},'../lib/supabase':{supabase:{rpc:(name,args)=>{calls.push({name,args});return {abortSignal:async()=>({data,error})};}}}},{Date:{parse:Date.parse,now(){throw Error('Client clock forbidden');}}})};}
const signal=()=>new AbortController().signal;
for(const [name,rpc,data] of [['getFundedCompletionStatus','get_my_funded_movement_completion_status',pending()],['requestFundedCompletion','request_my_funded_movement_completion',pending()],['confirmFundedCompletion','confirm_my_funded_movement_completion',completed('requester_confirmed')],['disputeFundedCompletion','dispute_my_funded_movement_completion',review()]]){
 test('0087 '+name+' exact bounded arguments',async()=>{const h=service([data]);await h.api[name](need,signal());assert.equal(h.calls[0].name,rpc);assert.equal(JSON.stringify(h.calls[0].args),JSON.stringify(name==='disputeFundedCompletion'?{p_movement_need_id:need,p_reason_category:'completion_concern'}:{p_movement_need_id:need}));});
 test('0087 '+name+' invalid selectors and pre-abort never RPC',async()=>{for(const value of [null,'bad',{},[need]]){const h=service();await assert.rejects(()=>h.api[name](value,signal()));assert.equal(h.calls.length,0);}const h=service(),a=new AbortController();a.abort();await assert.rejects(()=>h.api[name](need,a.signal));assert.equal(h.calls.length,0);});
 test('0087 '+name+' backend errors stay generic',async()=>{await assert.rejects(()=>service(null,{message:'SECRET wallet SQL'}).api[name](need,signal()),/^Error: unavailable$/);});
}
for(const method of ['requester_confirmed','response_timeout'])test('0087 completion truth '+method+' accepts regressed metadata',async()=>{assert.equal((await service([completed(method)]).api.getFundedCompletionStatus(need,signal())).completionMethod,method);});
for(const patch of [{response_deadline_at:null},{response_deadline_at:'infinity'},{response_deadline_at:'2026-02-30T00:00:00Z'},{can_dispute_completion:'true'},{dispute_active:1},{completion_method:'admin'},{completion_method:'requester_confirmed'},{dispute_active:true},{can_dispute_completion:false},{wallet_id:need},{reason_category:'private'},{alignment_id:need},{journey_state:['in_progress']},{settlement_state:'timeout_pending'},{settlement_state:'under_review'},{completed_at:'2099-01-01T00:00:00Z'}])test('0087 malformed projection '+JSON.stringify(patch),async()=>{await assert.rejects(()=>service([pending(patch)]).api.getFundedCompletionStatus(need,signal()));});
test('0087 review requires requested in-progress state with no decisive controls',async()=>{const s=await service([review()]).api.disputeFundedCompletion(need,signal());assert.equal(s.disputeActive,true);assert.equal(s.canConfirmCompletion,false);assert.equal(s.canDisputeCompletion,false);await assert.rejects(()=>service([pending()]).api.disputeFundedCompletion(need,signal()));});
test('0087 response deadline retains exact twelve-hour same-event derivation',async()=>{for(const deadline of ['2026-10-03T21:59:59Z','2026-10-03T22:00:00.000001Z'])await assert.rejects(()=>service([pending({response_deadline_at:deadline})]).api.getFundedCompletionStatus(need,signal()));assert.equal((await service([pending({completion_requested_at:'2026-10-03T10:00:00.123456Z',response_deadline_at:'2026-10-03T22:00:00.123456Z'})]).api.getFundedCompletionStatus(need,signal())).canDisputeCompletion,true);});
test('0087 caller cannot serialize financial identity, method, deadline or timestamps',async()=>{const h=service([review()]);await h.api.disputeFundedCompletion(need,signal(),{requested_at:'forged',response_deadline_at:'forged',completion_method:'response_timeout',requester_identity:need,amount:999});assert.deepEqual(Object.keys(h.calls[0].args),['p_movement_need_id','p_reason_category']);});
function render(status){const jsx=(type,props)=>({type,props});return load('src/components/FundedCompletion.tsx',{'react/jsx-runtime':{jsx,jsxs:jsx},'react-native':{View:'View',Text:'Text',Pressable:'Pressable'},'../hooks/useFundedCompletion':{useFundedCompletion:()=>({state:{status,busy:false,error:false},confirmCompletion(){},disputeCompletion(){},refresh(){}})}}).FundedCompletion({movementNeedId:need});}
function text(e){return e==null?'':typeof e==='string'?e:Array.isArray(e)?e.map(text).join(' '):text(e.props?.children);}
function buttons(e){if(!e||typeof e!=='object')return [];if(Array.isArray(e))return e.flatMap(buttons);return [...(e.type==='Pressable'?[text(e)]:[]),...buttons(e.props?.children)];}
test('0087 requester UI exactly Confirm completed and Dispute substantive actions',()=>{const s={settlementState:'awaiting_confirmation',responseDeadlineAt:'2026-10-03T22:00:00Z',canConfirmCompletion:true,canDisputeCompletion:true};const tree=render(s);assert.deepEqual(buttons(tree),['Confirm completed','Dispute','Refresh movement completion']);assert.match(text(tree),/If no dispute is made before the response period ends, the movement will be treated as completed/);assert.doesNotMatch(text(tree),/do nothing|accept timeout|later|not now|refund|winner/i);});
test('0087 offerer waiting and review states have no requester actions',()=>{for(const s of [{settlementState:'awaiting_confirmation',responseDeadlineAt:'deadline'},{settlementState:'under_review',disputeActive:true},{settlementState:'settled',completionMethod:'response_timeout'}])assert.deepEqual(buttons(render(s)),['Refresh movement completion']);assert.match(text(render({disputeActive:true})),/held movement amount remains on hold/);});
test('0087 UI and client never decide window expiry using device time',()=>{for(const p of ['src/components/FundedCompletion.tsx','src/services/fundedCompletionService.ts','src/state/fundedCompletionController.ts','src/hooks/useFundedCompletion.ts'])assert.doesNotMatch(read(p),/Date\.now|new Date|responseDeadlineAt\s*[<>]|response_deadline_at\s*[<>]/);});
const create=()=>load('src/state/fundedCompletionController.ts').createFundedCompletionController;
for(const action of ['confirmCompletion','disputeCompletion'])test('0087 '+action+' duplicate taps and stale identity fail closed',async()=>{let resolve,mutations=0,used;const wait=new Promise(r=>resolve=r);const api={read:async()=>({canConfirmCompletion:true,canDisputeCompletion:true}),confirm:async(n,s)=>{mutations++;used=s;return wait;},dispute:async(n,s)=>{mutations++;used=s;return wait;}};const c=create()(need,api);c.activate();await c.refresh();const p=c[action]();await c[action]();assert.equal(mutations,1);c.clear();assert(used.aborted);resolve({disputeActive:true});await p;assert.equal(c.getSnapshot().status,null);});
test('0087 mutation response waits for fresh read and read failure clears controls',async()=>{let reads=0;const c=create()(need,{read:async()=>{if(++reads===1)return {canDisputeCompletion:true};throw Error('read failed');},dispute:async()=>({disputeActive:true})});c.activate();await c.refresh();await c.disputeCompletion();assert.equal(reads,2);assert.equal(c.getSnapshot().status,null);assert.equal(c.getSnapshot().error,true);});
test('0087 refresh stays read-only at client boundary; backend applies lazy policy',async()=>{const calls=[];const c=create()(need,{read:async()=>{calls.push('read');return {canDisputeCompletion:false};},dispute:async()=>calls.push('dispute'),confirm:async()=>calls.push('confirm')});c.activate();await c.refresh();await c.disputeCompletion();assert.deepEqual(calls,['read']);});
for(const event of ['account','background','unmount'])test('0087 dispute hook invalidates late mutation on '+event,async()=>{
 let auth,app,cleanup,get,resolve,used;const wait=new Promise(r=>resolve=r),calls=[];const AppState={currentState:'active',addEventListener:(_e,f)=>{app=f;return {remove(){}};}};
 const model=load('src/hooks/useFundedCompletion.ts',{react:{useMemo:f=>f(),useCallback:f=>f,useSyncExternalStore:(_s,g)=>{get=g;return g();}},'expo-router':{useFocusEffect:f=>{cleanup=f();}},'react-native':{AppState},'../lib/supabase':{supabase:{auth:{onAuthStateChange:f=>{auth=f;return {data:{subscription:{unsubscribe(){}}}};}}}},'../state/fundedCompletionController':{createFundedCompletionController:create()},'../services/fundedCompletionService':{getFundedCompletionStatus:async()=>{calls.push('read');return {canDisputeCompletion:true};},disputeFundedCompletion:async(n,s)=>{used=s;calls.push('dispute');return wait;}}}).useFundedCompletion(need);
 assert.equal(calls.length,0);auth('SIGNED_IN',{user:{id:'requester'}});await new Promise(r=>setImmediate(r));const p=model.disputeCompletion();if(event==='account')auth('SIGNED_IN',{user:{id:'other'}});else if(event==='background'){AppState.currentState='background';app();}else cleanup();assert(used.aborted);resolve({disputeActive:true});await p;assert.notEqual(get().status?.disputeActive,true);cleanup();
});
test('0087 historical migrations 0001–0086 exact normalized HEAD bytes',()=>{const prefix=cp.execFileSync('git',['rev-parse','--show-prefix'],{encoding:'utf8'}).trim();for(const f of fs.readdirSync('supabase/migrations').filter(f=>/^\d{4}_/.test(f)&&Number(f.slice(0,4))<=86)){assert.equal(read('supabase/migrations/'+f),cp.execFileSync('git',['show','HEAD:'+prefix+'supabase/migrations/'+f],{encoding:'utf8'}).replace(/\r\n/g,'\n'),f);}});
test('0087 immutable private windows/reviews and no new admin or paid authority',()=>{for(const table of ['funded_completion_response_windows','funded_completion_disputes']){assert(sql.includes('CREATE TABLE private.'+table));assert(sql.includes('ALTER TABLE private.'+table+' ENABLE ROW LEVEL SECURITY'));assert(sql.includes('BEFORE UPDATE OR DELETE OR TRUNCATE ON private.'+table));}assert.match(sql,/interval '12 hours'/);assert.doesNotMatch(sql,/cron\.|admin_settlement|DISABLE TRIGGER|session_replication_role|SET CONSTRAINTS|UPDATE private.funded_movement_completions/);});
test('0087 historical completion/coordination validators have no live clock or independent chronology',()=>{for(const name of ['assert_funded_completion','assert_funded_coordination_entry','validate_completed_movement_rating']){const start=sql.indexOf('CREATE OR REPLACE FUNCTION private.'+name+'(');const b=sql.slice(start,sql.indexOf('\nCREATE ',start+1));assert.doesNotMatch(b,/clock_timestamp\(\)|requested_at<j.started_at|completed_at<request.requested_at|started_at<request.requested_at|submitted_at<completed/);}});
test('0087 shared settlement retains complete audited economics body',()=>{const old=require('../docs/0087-installed-baseline-audit.json').functions.find(f=>f.name==='public.confirm_my_funded_movement_completion').body;const fragment=old.slice(old.indexOf(' -- All member gates'),old.indexOf('  stamp:=clock_timestamp();'));assert(sql.includes(fragment),'all account/topology/overflow/provisioning checks retained');const cte=old.slice(old.indexOf('  WITH evidence AS ('),old.indexOf('  PERFORM private.assert_funded_coordination_entry(a.id);',old.indexOf('  WITH evidence AS ('))).replace('VALUES(a.id,g.id,j.id,stamp)','VALUES(a.id,g.id,j.id,stamp,p_method)');assert(sql.includes(cte),'complete ordered component/ledger/lifecycle CTE retained');assert.doesNotMatch(sql,/0\.15|0\.70|calculate_financial_quote/);});
test('0087 receipt admission owns deadline classification for direct stale confirmation',()=>{
 const start=sql.indexOf('CREATE OR REPLACE FUNCTION private.require_funded_completion_actor()'),body=sql.slice(start,sql.indexOf('\nCREATE ',start+1));
 assert.equal((body.match(/clock_timestamp\(\)/g)||[]).length,1);assert.match(body,/w\.alignment_id=a\.id AND w\.financial_agreement_id=g AND w\.journey_id=j\.id/);assert.match(body,/w\.requested_at=j\.completion_requested_at/);assert.match(body,/IF NEW\.completed_at>=deadline THEN\s+NEW\.completion_method:='response_timeout'/);
 const engine=sql.slice(sql.indexOf('CREATE FUNCTION private.finalize_funded_completion('),sql.indexOf('DROP FUNCTION public.get_my_funded_movement_completion_status'));
 assert.doesNotMatch(engine,/clock_timestamp\(\)/);assert(engine.indexOf('currency=g.currency FOR UPDATE')<engine.indexOf('stamp:=NULL;'));assert(engine.includes('VALUES(a.id,g.id,j.id,stamp,p_method)'));
});
