const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
function load(file,stubs={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,{exports,Error,Date,AbortController,setTimeout,clearTimeout,...globals,require:n=>n in stubs?stubs[n]:require(n)});return exports;}
const need='11111111-1111-4111-8111-111111111111';
const row=(x={})=>({meeting_point_text:null,meeting_point_revision:null,journey_state:'not_started',start_requested_at:null,started_at:null,can_edit_meeting_point:true,can_request_start:false,can_confirm_start:false,...x});
function service(result=[row()],error=null){const calls=[];const api=load('src/services/meetingJourneyService.ts',{'./coordinationService':{validMovementNeed:v=>typeof v==='string'&&v===need},'../lib/supabase':{supabase:{rpc:(name,args)=>{calls.push({name,args});return {abortSignal:async signal=>{assert(signal instanceof AbortSignal);return {data:result,error};}};}}}});return {api,calls};}
const signal=()=>new AbortController().signal;
for(const input of ['bad',null,[need]])test(`malformed ID ${JSON.stringify(input)} never calls RPC`,async()=>{const h=service();await assert.rejects(()=>h.api.getMeetingJourneyStatus(input,signal()));assert.equal(h.calls.length,0);});
test('safe status projection excludes all internal fields',async()=>{const h=service([row({member_id:'SECRET',journey_id:'SECRET',latitude:5})]);const r=await h.api.getMeetingJourneyStatus(need,signal());assert.equal(r.meetingPointText,null);assert(!JSON.stringify(r).includes('SECRET'));assert(!('latitude' in r));});
test('set sends only need text expected revision',async()=>{const h=service();await h.api.setMeetingPoint(need,'  Bus stop  ',null,signal());assert.deepEqual(JSON.parse(JSON.stringify(h.calls[0])),{name:'set_my_movement_meeting_point',args:{p_movement_need_id:need,p_place_text:'Bus stop',p_expected_revision:null}});});
for(const action of ['requestMovementStart','confirmMovementStart'])test(`${action} sends no actor/status/GPS fields`,async()=>{const h=service();await h.api[action](need,signal());assert.deepEqual(Object.keys(h.calls[0].args),['p_movement_need_id']);});
test('conflict code is safe; SQL error is never exposed',async()=>{for(const [code,message] of [['40001','conflict'],['42501','unavailable']]){const h=service(null,{code,message:'SECRET'});await assert.rejects(()=>h.api.getMeetingJourneyStatus(need,signal()),new RegExp(message));}});
for(const patch of [{journey_state:'started'},{can_request_start:true},{start_requested_at:'2026-01-01T00:00:00Z'},{journey_state:'in_progress'},{can_confirm_start:true}])test(`inconsistent backend shape fails closed ${JSON.stringify(patch)}`,async()=>{await assert.rejects(()=>service([row(patch)]).api.getMeetingJourneyStatus(need,signal()));});
test('empty unauthorized result contains no meeting point',async()=>{assert.equal(await service([]).api.getMeetingJourneyStatus(need,signal()),null);});
const {createMeetingController:create}=load('src/state/meetingJourneyController.ts');
const status=(x={})=>({meetingPointText:null,meetingPointRevision:null,journeyState:'not_started',startRequestedAt:null,startedAt:null,canEditMeetingPoint:true,canRequestStart:false,canConfirmStart:false,...x});
const defer=()=>{let resolve;const promise=new Promise(r=>resolve=r);return {promise,resolve};};
function controller(initial=status(),extra={}){const calls=[];const api={read:async()=>initial,set:async(n,t,r)=>{calls.push(['set',n,t,r]);return status({meetingPointText:t,meetingPointRevision:1,canRequestStart:true});},request:async()=>{calls.push(['request']);return status({meetingPointText:'Bus stop',meetingPointRevision:1,startRequestedAt:'2026-01-01T00:00:00Z',canEditMeetingPoint:false});},confirm:async()=>{calls.push(['confirm']);return status({journeyState:'in_progress',startedAt:'2026-01-01T00:00:00Z',canEditMeetingPoint:false});},...extra};const c=create(need,api);c.activate();return {c,calls};}
test('extra traveller read only even with local meeting text',async()=>{const h=controller(status({meetingPointText:'Bus stop',meetingPointRevision:1,canEditMeetingPoint:false}));await h.c.refresh();await h.c.save('No');await h.c.requestStart();await h.c.confirmStart();assert.equal(h.calls.length,0);});
test('backend permits edit after activation; save alone never starts',async()=>{const h=controller();await h.c.refresh();await h.c.save('Bus stop');assert.equal(h.c.getSnapshot().status.journeyState,'not_started');assert.equal(h.c.getSnapshot().status.canEditMeetingPoint,true);});
test('backend start request freezes editing and remains not started',async()=>{const h=controller(status({meetingPointText:'Bus stop',meetingPointRevision:1,canRequestStart:true}));await h.c.refresh();await h.c.requestStart();await h.c.save('No');assert.equal(h.calls.length,1);assert.equal(h.c.getSnapshot().status.canEditMeetingPoint,false);assert.equal(h.c.getSnapshot().status.journeyState,'not_started');});
test('duplicate starts issue only one active request',async()=>{const d=defer();let n=0;const h=controller(status({canRequestStart:true}),{request:async()=>{n++;return d.promise;}});await h.c.refresh();const p=h.c.requestStart();await h.c.requestStart();assert.equal(n,1);d.resolve(status());await p;});
test('duplicate edits issue only one active request',async()=>{const d=defer();let n=0;const h=controller(status(),{set:async()=>{n++;return d.promise;}});await h.c.refresh();const p=h.c.save('A');await h.c.save('B');assert.equal(n,1);d.resolve(status());await p;});
test('clear on account/background invalidates old response before newer refresh',async()=>{const d=defer();let n=0;const h=controller(status(),{read:async()=>++n===1?d.promise:status({meetingPointText:'New',meetingPointRevision:1})});const p=h.c.refresh();h.c.clear();assert.equal(h.c.getSnapshot().status,null);h.c.activate();await h.c.refresh();d.resolve(status({meetingPointText:'Old',meetingPointRevision:1}));await p;assert.equal(h.c.getSnapshot().status.meetingPointText,'New');});
test('conflict clears stale point and requires explicit refresh',async()=>{const h=controller(status(),{set:async()=>{throw Error('conflict');}});await h.c.refresh();await h.c.save('A');assert.equal(h.c.getSnapshot().error,'conflict');assert.equal(h.c.getSnapshot().status,null);});
function text(e){if(e==null)return '';if(typeof e==='string')return e;if(Array.isArray(e))return e.map(text).join(' ');if(typeof e.type==='function')return text(e.type(e.props));return text(e.props?.children);}
function render(s){return text(load('src/components/MeetingJourney.tsx',{react:{useState:v=>[v,()=>{}]},'react-native':{View:'View',Text:'Text',TextInput:'TextInput',Pressable:'Pressable'},'../hooks/useMeetingJourney':{useMeetingJourney:()=>({state:{status:s,busy:false,error:null}})}}).MeetingJourney({movementNeedId:need}));}
test('UI no meeting point has no start button without capability',()=>{const t=render(status());assert(t.includes('No meeting point has been set yet.'));assert(t.includes('Set meeting point'));assert(!t.includes('Start journey'));assert(!t.includes('Journey started'));});
test('UI extra traveller has no edit/request/confirm controls',()=>{const t=render(status({canEditMeetingPoint:false}));assert(!/Set meeting point|Start journey|Confirm start/.test(t));});
test('pending confirm and started copy require backend evidence',()=>{const pending=render(status({meetingPointText:'Bus stop',meetingPointRevision:1,startRequestedAt:'2026-01-01T00:00:00Z',canEditMeetingPoint:false,canConfirmStart:true}));assert(pending.includes('Waiting for start confirmation'));assert(pending.includes('Confirm start'));assert(!pending.includes('Change meeting point'));assert(!pending.includes('Journey started'));assert(render(status({journeyState:'in_progress',startedAt:'2026-01-01T00:00:00Z',canEditMeetingPoint:false})).includes('Journey started'));});
test('no location, local biometric/payment or raw identity authority in new client code',()=>{for(const p of ['src/services/meetingJourneyService.ts','src/state/meetingJourneyController.ts','src/hooks/useMeetingJourney.ts','src/components/MeetingJourney.tsx'])assert.doesNotMatch(fs.readFileSync(p,'utf8'),/expo-location|latitude|longitude|geofence|faceReady|paymentSucceeded|memberId|journeyId|alignmentId/);});
function hookHarness(){let auth,app,cleanup,snapshot;const calls=[];const AppState={currentState:'active',addEventListener:(_,fn)=>{app=fn;return {remove(){}};}};const use=load('src/hooks/useMeetingJourney.ts',{react:{useMemo:fn=>fn(),useCallback:fn=>fn,useSyncExternalStore:(_s,get)=>{snapshot=get;return get();}},'expo-router':{useFocusEffect:fn=>{cleanup=fn();}},'react-native':{AppState},'../lib/supabase':{supabase:{auth:{onAuthStateChange:fn=>{auth=fn;return {data:{subscription:{unsubscribe(){}}}};}}}},'../state/meetingJourneyController':{createMeetingController:create},'../services/meetingJourneyService':{getMeetingJourneyStatus:async()=>{calls.push('read');return status({meetingPointText:'Bus stop',meetingPointRevision:1});},setMeetingPoint:async()=>{calls.push('write');return status();},requestMovementStart:async()=>{calls.push('start');return status();},confirmMovementStart:async()=>{calls.push('confirm');return status();}}}).useMeetingJourney;const model=use(need);return {model,calls,state:()=>snapshot(),login:id=>auth('SIGNED_IN',id?{user:{id}}:null),background:()=>{AppState.currentState='background';app();},resume:()=>{AppState.currentState='active';app();},cleanup:()=>cleanup()};}
const flush=()=>new Promise(r=>setImmediate(r));
test('hook account/background clears private state; foreground reads only',async()=>{const h=hookHarness();h.login('a');await flush();assert.equal(h.state().status.meetingPointText,'Bus stop');h.background();assert.equal(h.state().status,null);h.resume();await flush();assert.deepEqual(h.calls,['read','read']);h.login('b');assert.equal(h.state().status,null);await flush();h.login(null);assert.equal(h.state().status,null);h.cleanup();});
test('hook unmount disables all actions and clears state',async()=>{const h=hookHarness();h.login('a');await flush();h.cleanup();assert.equal(h.state().status,null);await h.model.save('Secret');await h.model.requestStart();assert.deepEqual(h.calls,['read']);});
for(const place of ['','  ','x'.repeat(201)])test(`invalid place length ${place.length} makes no write`,async()=>{const h=service();await assert.rejects(()=>h.api.setMeetingPoint(need,place,null,signal()));assert.equal(h.calls.length,0);});
for(const revision of ['1',1.5,0,-1,NaN,[1]])test(`revision is never coerced: ${JSON.stringify(revision)}`,async()=>{const h=service();await assert.rejects(()=>h.api.setMeetingPoint(need,'Bus stop',revision,signal()));assert.equal(h.calls.length,0);});
test('legitimate Unicode Nigerian place name is preserved',async()=>{const h=service();const place='\u1eccj\u00e0 bus stop, Lekki';await h.api.setMeetingPoint(need,place,null,signal());assert.equal(h.calls[0].args.p_place_text,place);});
